Work with introducing a summary for inspect.

diff --git a/dbwebb2-inspect b/dbwebb2-inspect
--- a/dbwebb2-inspect
+++ b/dbwebb2-inspect
@@ -820,6 +820,10 @@ function assert()
 
         printf "\n\n$MSG_WARNING %s\n" "$MESSAGE"
         [ -z "$error" ] || printf "%s\n\n" "$error"
+
+        ASSERTS_SUMMARY="$ASSERTS_SUMMARY\n $MSG_WARNING $MESSAGE\n"
+    else
+        ASSERTS_SUMMARY="$ASSERTS_SUMMARY."
     fi
 
     return $status
@@ -828,45 +832,66 @@ function assert()
 
 
 #
-# Perform an assert on exit value returned
-# TODO Check if this is really needed by python inspect
+# Add details to the assert summary, for example when a new section is
+# started, to visualise and greoup the asserts into sections.
 #
-assertExit()
+function assertSummaryAdd()
 {
-    EXPECTED=$1
-    TEST=$2
-    MESSAGE=$3
-    ASSERTS=$(( $ASSERTS + 1 ))
+    local message="$1"
+    local space="            "
+    # ten="          " 
+    # forty="$ten$ten$ten$ten" 
+    # y="very short text"
+    # y="${y:0:40}${forty:0:$((40 - ${#y}))}"
+    # echo "'${y}'"
 
-    bash -c "$TEST" &> "$TMPFILE"
-    STATUS=$?
-    ERROR=$( cat "$TMPFILE" )
-    rm -f "$TMPFILE"
-
-    if [ $STATUS -ne $EXPECTED ]; then
-        FAULTS=$(( $FAULTS + 1 ))
-
-        printf "\n$TEST"
-        printf "\n\n$MSG_FAILED $MESSAGE\n"
-        [ -z "$ERROR" ] || printf "$ERROR\n\n"
-
-        return 1
-    fi
-
-    return 0
-
+    message="${message:0:12}${space:0:$((12 - ${#message}))}"
+    ASSERTS_SUMMARY="$ASSERTS_SUMMARY\n# $message"
 }
+
+
+
+# #
+# # Perform an assert on exit value returned
+# # TODO Check if this is really needed by python inspect
+# # OBSOLETE Not used
+# #
+# assertExit()
+# {
+#     EXPECTED=$1
+#     TEST=$2
+#     MESSAGE=$3
+#     ASSERTS=$(( $ASSERTS + 1 ))
+# 
+#     bash -c "$TEST" &> "$TMPFILE"
+#     STATUS=$?
+#     ERROR=$( cat "$TMPFILE" )
+#     rm -f "$TMPFILE"
+# 
+#     if [ $STATUS -ne $EXPECTED ]; then
+#         FAULTS=$(( $FAULTS + 1 ))
+# 
+#         printf "\n$TEST"
+#         printf "\n\n$MSG_FAILED $MESSAGE\n"
+#         [ -z "$ERROR" ] || printf "$ERROR\n\n"
+# 
+#         return 1
+#     fi
+# 
+#     return 0
+# 
+# }
 
 
 
 
 #
 # Clean up and output results from asserts
+# TODO Seems to be used by validate
 #
 function assertResults()
 {
-    if [ $FAULTS -gt 0 ]
-        then
+    if [ $FAULTS -gt 0 ]; then
         printf "\n\n$MSG_FAILED"
         printf " Asserts: $ASSERTS Faults: $FAULTS\n\n"
         exit 1
@@ -3147,6 +3172,7 @@ function inspectIntro()
 {
     local target="me/$KMOM"
 
+    #assertSummaryAdd "intro"
     headerForTest "-- $DBW_COURSE $KMOM" "-- ${DBW_WWW}$DBW_COURSE/$KMOM"
     checkKmomDir "$target"
     publishKmom
@@ -3172,6 +3198,7 @@ function inspectMe()
         assignment="\n-- ${DBW_WWW}$assignment"
     fi
 
+    assertSummaryAdd "me-page"
     headerForTest "-- me-page" "-- ${DBW_WWW}$DBW_COURSE/$KMOM#resultat_redovisning$assignment" 
     checkKmomDir "$target"
     viewFileTree "$target"
@@ -3198,6 +3225,7 @@ function inspectLab()
     local urlfile="$5"
     local target="me/$KMOM/$lab"
 
+    assertSummaryAdd "$lab"
     headerForTest "-- $lab" "-- ${DBW_WWW}$url"
     viewFileTree "$target"
     #openFilesInEditor "$target"
@@ -3296,6 +3324,7 @@ dbwebbInspectTargetNotReadable()
 #
 dbwebbInspectCheckEnvironment()
 {
+    assertSummaryAdd "general"
     headerForTest "-- dbwebb inspect"
     printUrl "" "me"
     #openFilesInEditor "me"
@@ -3768,16 +3797,28 @@ esac
 # Clean up and output results
 #
 headerForTest "-- dbwebb inspect summary"
+# assertResults # Use this, but align with validate
 
 if [ $FAULTS -gt 0 ]; then
-        printf "\n\n$MSG_FAILED"
-        STATUS=1
+    printf "\n\n$MSG_FAILED"
+    STATUS=1
 else 
-        printf "\n\n$MSG_OK"
-        STATUS=0
+    printf "\n\n$MSG_OK"
+    STATUS=0
 fi
 
-printf " Asserts: $ASSERTS Faults: $FAULTS\n"
+printf " Asserts: $ASSERTS Faults: $FAULTS"
+
+#printf "\n### Assert details\n\n"
+printf "$ASSERTS_SUMMARY\n"
+
+if [ $STATUS -eq 0 ]; then
+    printf "$MSG_OK Inspect PASSED all tests :-)\n\n"
+else 
+    printf "$MSG_FAILED Inspect FAILED to pass all tests :-|\n\n"
+fi
+
 #pressEnterToContinue
 #[[ $COPY_DIR ]] && rm -rf "$COPY_DIR"
+
 exit $STATUS
