Enable dbwebb exam correct to autocorrect an exam though .dbwebb/correct.bash.

diff --git a/dbwebb2 b/dbwebb2
--- a/dbwebb2
+++ b/dbwebb2
@@ -30,7 +30,7 @@
 #
 # Current version
 #
-DBW_VERSION="v2.1.3 (2018-05-30)"
+DBW_VERSION="v2.1.4 (2018-06-28)"
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -506,6 +506,26 @@ die()
 verboseDone()
 {
     [[ $SILENT ]] || printf "$MSG_DONE $1\\n" 
+}
+
+
+
+#
+# Print out information details that command partly failed.
+#
+verboseWarning()
+{
+    [[ $SILENT ]] || printf "$MSG_WARNING $1\\n"
+}
+
+
+
+#
+# Print out information details that command has failed.
+#
+verboseFail()
+{
+    [[ $SILENT ]] || printf "$MSG_FAILED $1\\n"
 }
 
 
@@ -1209,6 +1229,7 @@ function usageExam ()
 "Usage: dbwebb [options] exam <command> [arguments]"
 ""
 "Command:"
+"  correct                 Correct the exam (if supported)."
 "  help                    Print this help and usage message."
 "  list|ls                 View Active, Planned and Passed exams."
 "  receipt <target>        Get the receipt for an exam."
@@ -1960,6 +1981,11 @@ dbwebb-exam()
             exit 0
         ;;
 
+        correct)
+            dbwebb-exam-correct "$what"
+            exit 0
+        ;;
+
         *)
             badUsageExam "$MSG_FAILED exam subcommand not recognized."
             exit 2
@@ -2143,6 +2169,43 @@ dbwebb-exam-receipt()
         || die "Failed to get receipt."
 
     verboseDone "Review your receipt."
+}
+
+
+
+#
+# Get the reciept for an exam.
+#
+dbwebb-exam-correct()
+{
+    local what="$1"
+    local subdir=
+    local where=
+    local correct=
+
+    checkIfValidConfigOrExit
+    checkIfValidCourseRepoOrExit
+
+    subdir="$( mapCmdToDir $what )"
+    where="$DBW_COURSE_DIR/$subdir"
+
+    checkIfValidCombination "$subdir" "$what"
+    checkIfSubdirExistsOrProposeInit "$where"
+
+    verbose "Correcting the exam $DBW_COURSE:$what..."
+
+    correct="$where/.dbwebb/correct.bash"
+    if [ -f $correct ]; then
+        if $correct; then
+            verboseDone "The exam is corrected and graded as passed :-)"
+        else
+            verboseWarning "The exam is corrected, but was graded as NOT passed :-|"
+            exit 1
+        fi
+    else
+        verboseFail "There is no auto correcting program installed."
+        exit 1
+    fi 
 }
 
 
