Corrected get_realpath to work with both dirs and files.

diff --git a/dbwebb2-validate b/dbwebb2-validate
--- a/dbwebb2-validate
+++ b/dbwebb2-validate
@@ -81,10 +81,23 @@ publishChmod()
 #
 function get_realpath()
 {
-    [[ ! -e "$1" ]] && return 1 # failure : file does not exist.
-    [[ -n "$no_symlinks" ]] && local pwdp='pwd -P' || local pwdp='pwd' # do symlinks.
-    echo "$( cd "$( echo "${1%/*}" )" 2>/dev/null; $pwdp )"/"${1##*/}" # echo result.
-    return 0 # success
+    # failure : file does not exist.
+    [[ ! -e "$1" ]] && return 1
+
+    # do symlinks.
+    [[ -n "$no_symlinks" ]] && local pwdp='pwd -P' || local pwdp='pwd'
+
+    # Path to dir, without eventual filename
+    local path="$( cd "$( echo "${1%/*}" )" 2>/dev/null; $pwdp )"
+
+    if [ -d "$1" ]; then
+        path="$( cd "$( echo "$1" )" 2>/dev/null; $pwdp )"
+    elif [ -f "$1" ]; then
+        path="$path/${1##*/}"
+    fi
+
+    echo "$path"
+    return 0
 }
 
 
@@ -608,7 +621,7 @@ function getPathToDirectoryFor
         echo "$command"
     elif [ -z "$dir" -a -d "$DBW_CURRENT_DIR/$command" ]; then
         echo "$DBW_CURRENT_DIR/$command"
-    elif [ -d "$DBW_COURSE_DIR" -a -d "$DBW_COURSE_DIR/$dir" ]; then
+    elif [ ! -z "$dir" -a -d "$DBW_COURSE_DIR" -a -d "$DBW_COURSE_DIR/$dir" ]; then
         echo "$DBW_COURSE_DIR/$dir"
     else
         printf "\n$MSG_FAILED The item '$command' was mapped to directory '$dir' which is not a valid directory."
@@ -1105,6 +1118,9 @@ YAML_OPTIONS=""
 #EXCLUDE_PATHS='\*/webgl/\* \*/libs/\* \*/lib/\* \*/node_modules/\*'
 EXCLUDE_PATHS='\*/example/webgl/\* \*/libs/\* \*/lib/\* \*/node_modules/\* \*/platforms/\* \*/plugins/\* \*/docs/api/\* \*/vendor/\* \*/3pp/\* \*/example/lekplats/\* \*/css/anax-grid/\* \*/me/anax-flat/\* \*/cache/\* \*/build/\* \*/.git/\* \*/slide/\*'
 EXCLUDE_FILES='phpliteadmin\* \*.min.\* \*.tpl.php font-awesome.css lessc.inc.php'
+INCLUDE_PATHS='' #'\*/platforms/browser/www/\*'
+#EXCLUDE_PATHS="*/example/webgl/* */libs/* */lib/* */node_modules/* */platforms/* */plugins/* */docs/api/* */vendor/* */3pp/* */example/lekplats/* */css/anax-grid/* */me/anax-flat/* */cache/* */build/* */.git/* */slide/*"
+#EXCLUDE_FILES="phpliteadmin* *.min.* *.tpl.php font-awesome.css lessc.inc.php"
 
 
 
@@ -1185,21 +1201,20 @@ function checkInstalledValidateTools
 #
 function getFindExpression
 {
-    local ignorePaths
-    local ignoreFiles
-    local findExpression
-    local ignoreExtension="$1"
+    local dir="$1"
+    local extension="$2"
+    local includeExclude
+    local findExtension=
 
-    ignorePaths=$( printf " -not -path %s " $( echo $EXCLUDE_PATHS ) )
-    ignoreFiles=$( printf " -not -name %s " $( echo $EXCLUDE_FILES ) )
+    includeExclude="$( printf " -not -path %s " $( echo $EXCLUDE_PATHS ) )"
+    includeExclude="$includeExclude $( printf " -not -name %s " $( echo $EXCLUDE_FILES ) )"
+    #includePaths=$( printf " -path %s " $( echo $INCLUDE_PATHS ) )
 
-    if [ -z "$ignoreExtension" ]; then
-        findExpression=$( echo "find \"$dir/\" -type f -name \*.$extension $ignorePaths $ignoreFiles" )
-    else
-        findExpression=$( echo "find \"$dir/\" $ignorePaths $ignoreFiles" )
+    if [ ! -z "$extension" ]; then
+        findExtension="-type f -name \"*.$extension\""
     fi
-    
-    echo $findExpression
+
+    echo "find \"$dir/\" $findExtension $includeExclude"
 }
 
 
@@ -1217,12 +1232,11 @@ function validateCommand()
     local onlyExitStatus="$6"
     local counter=0
     local findExpression=
-    local ignoreExtension="$7"
 
     if hash "$cmd" 2>/dev/null; then
         printf "\n *.$extension using $cmd"
 
-        findExpression=$( getFindExpression $ignoreExtension )
+        findExpression="$( getFindExpression "$dir" "$extension" )"
 
         [[ $optDryRun ]] && echo "$findExpression"
 
@@ -1274,8 +1288,8 @@ function validate()
     [[ $ENABLE_ALL || ! $DISABLE_CHECKBASH ]] && validateCommand "$dir" "$CHECKBASH" "bash" "$CHECKBASH_OPTIONS"
     [[ $ENABLE_ALL || ! $DISABLE_CHECKSH ]]   && validateCommand "$dir" "$CHECKSH" "sh" "$CHECKSH_OPTIONS"
     [[ $ENABLE_ALL || ! $DISABLE_YAML ]]      && validateCommand "$dir" "$YAML" "yml" "$YAML_OPTIONS" "> /dev/null"
-    [[ $ENABLE_ALL || ! $DISABLE_FILE_CRLF ]] && validateCommand "$dir" "$FILE_CRLF" "" "$FILE_CRLF_OPTIONS" '| grep CRLF; test $? -eq 1' "" "allExtensions"
-    [[ $ENABLE_ALL || ! $DISABLE_FILE_BOM ]]  && validateCommand "$dir" "$FILE_BOM" "" "$FILE_BOM_OPTIONS" '| grep BOM; test $? -eq 1' "" "allExtensions"
+    [[ $ENABLE_ALL || ! $DISABLE_FILE_CRLF ]] && validateCommand "$dir" "$FILE_CRLF" "" "$FILE_CRLF_OPTIONS" '| grep CRLF; test $? -eq 1' ""
+    [[ $ENABLE_ALL || ! $DISABLE_FILE_BOM ]]  && validateCommand "$dir" "$FILE_BOM" "" "$FILE_BOM_OPTIONS" '| grep BOM; test $? -eq 1' ""
 }
 
 
@@ -1458,10 +1472,15 @@ done
 # Validate (and publish) the path choosen
 #
 dir="$( getPathToDirectoryFor "$command" )"
+echo "$dir"
+dir1="$( get_realpath "$dir" )"
+echo $dir1
+
 if [ ! -d "$dir" ]; then
     badUsage "$MSG_FAILED Directory '$command' is not a valid directory."
     exit 2
 fi
+#exit
 
 
 
