validate on studserver

diff --git a/dbwebb2 b/dbwebb2
--- a/dbwebb2
+++ b/dbwebb2
@@ -771,6 +771,11 @@ dbwebb-create()
     local subdir="$( mapCmdToDir $lab )"
     local where="$DBW_COURSE_DIR/$subdir"
     
+    if [ -z "$subdir" ]; then
+        printf "$MSG_FAILED Not a valid combination of '$DBW_COURSE' and '$lab'.\n"
+        exit 2
+    fi
+
     checkIfValidCourseRepoOrExit
 
     printf "Creating $DBW_COURSE $lab in '$where'.\n"
@@ -815,6 +820,9 @@ dbwebb-create()
             printf "\n answer.php"
             $myWget "$where/answer.php" "$DBW_LABURL/lab.php?answer-php&key=$key"
 
+            printf "\n CDbwebb.php"
+            $myWget "$where/CDbwebb.php" "$DBW_LABURL/lab.php?answer-php-assert&key=$key"
+
             printf "\n answer.json"
             $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
         ;;
@@ -828,15 +836,15 @@ dbwebb-create()
         ;;
 
         python)
-            printf "\n answer.json"
-            $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
-
             printf "\n answer.py"
             $myWget "$where/answer.py" "$DBW_LABURL/lab.php?answer-py&key=$key"
             chmod 755 "$where/answer.py"
 
             printf "\n Dbwebb.py"
             $myWget "$where/Dbwebb.py" "$DBW_LABURL/lab.php?answer-py-assert&key=$key"
+
+            printf "\n answer.json"
+            $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
         ;;
 
     esac
@@ -886,6 +894,7 @@ dbwebb-updateconfig()
 
 #
 # Specify the utilities used
+# TODO Remove these, not really needed.
 #
 ECHO="printf"
 GIT="git"
diff --git a/dbwebb2-validate b/dbwebb2-validate
--- a/dbwebb2-validate
+++ b/dbwebb2-validate
@@ -745,6 +745,11 @@ dbwebb-create()
     local subdir="$( mapCmdToDir $lab )"
     local where="$DBW_COURSE_DIR/$subdir"
     
+    if [ -z "$subdir" ]; then
+        printf "$MSG_FAILED Not a valid combination of '$DBW_COURSE' and '$lab'.\n"
+        exit 2
+    fi
+
     checkIfValidCourseRepoOrExit
 
     printf "Creating $DBW_COURSE $lab in '$where'.\n"
@@ -789,6 +794,9 @@ dbwebb-create()
             printf "\n answer.php"
             $myWget "$where/answer.php" "$DBW_LABURL/lab.php?answer-php&key=$key"
 
+            printf "\n CDbwebb.php"
+            $myWget "$where/CDbwebb.php" "$DBW_LABURL/lab.php?answer-php-assert&key=$key"
+
             printf "\n answer.json"
             $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
         ;;
@@ -802,15 +810,15 @@ dbwebb-create()
         ;;
 
         python)
-            printf "\n answer.json"
-            $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
-
             printf "\n answer.py"
             $myWget "$where/answer.py" "$DBW_LABURL/lab.php?answer-py&key=$key"
             chmod 755 "$where/answer.py"
 
             printf "\n Dbwebb.py"
             $myWget "$where/Dbwebb.py" "$DBW_LABURL/lab.php?answer-py-assert&key=$key"
+
+            printf "\n answer.json"
+            $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
         ;;
 
     esac
@@ -860,6 +868,7 @@ dbwebb-updateconfig()
 
 #
 # Specify the utilities used
+# TODO Remove these, not really needed.
 #
 ECHO="printf"
 GIT="git"
@@ -1022,9 +1031,18 @@ PYLINT="pylint"
 PYLINT_OPTIONS="-r n"
 
 PHP="php"
+PHP_OPTIONS="--syntax-check"
+
 PHPMD="phpmd"
+PHPMD_OPTIONS="text"
+
 PHPCS="phpcs"
+PHPCS_OPTIONS=""
+
 PHPUGLIFY=""
+
+PHPMINIFY="php"
+PHPMINIFY_OPTIONS="--strip"
 
 CHECKBASH="shellcheck"
 CHECKBASH_OPTIONS="--shell=bash"
@@ -1039,7 +1057,11 @@ YAML_OPTIONS=""
 
 if [[ $DBW_COURSE_DIR ]]; then
     HTML_MINIFIER_CONFIG="--config-file '$DBW_COURSE_DIR/.html-minifier.conf'"
-    PYLINT_CONFIG="--rcfile $DBW_COURSE_DIR/.pylintrc"
+    PYLINT_CONFIG="--rcfile '$DBW_COURSE_DIR/.pylintrc'"
+    PHPMD_CONFIG="'$DBW_COURSE_DIR/.phpmd.xml'"
+    PHPCS_CONFIG="--standard='$DBW_COURSE_DIR/.phpcs.xml'"
+else
+    PHPMD_CONFIG="cleancode,codesize,controversial,design,naming,unusedcode"
 fi
 
 
@@ -1066,6 +1088,7 @@ function checkInstalledValidateTools
     printf " html-minifier: %s\n" "$( checkCommand $HTML_MINIFIER )"
     printf " cleancss:      %s\n" "$( checkCommand $CLEANCSS )"
     printf " uglifyjs:      %s\n" "$( checkCommand $UGLIFYJS )"
+    printf " phpuglify:     %s\n" "$( checkCommand $PHPMINIFY )"
     printf " phpuglify:     %s\n" "$( checkCommand $PHPUGLIFY )"
 }
 
@@ -1165,9 +1188,11 @@ function validateCommand()
         printf "\n *.$extension using $cmd"
         for filename in $(find "$dir/" -type f -name \*.$extension); do
             if [[ $optDryRun ]]; then
-                printf "\n%s" "$cmd $options $filename"
+                printf "\n%s" "$cmd $options $filename $output"
             else
-                if [ -z $optOnly -o $optOnly == $extension ]; then
+                if [ -z $optOnly  ]; then
+                    assert 0 "$cmd $options $filename $output" "$cmd failed: $filename"
+                elif [ "$extension" == "$optOnly" ]; then
                     assert 0 "$cmd $options $filename $output" "$cmd failed: $filename"
                 fi
             fi
@@ -1194,12 +1219,12 @@ function validate()
     validateCommand "$dir" "$JSCS" "js"
     validateCommand "$dir" "$PYLINT" "py" "$PYLINT_OPTIONS $PYLINT_CONFIG" 
     validateCommand "$dir" "$PYLINT" "cgi" "$PYLINT_OPTIONS $PYLINT_CONFIG" 
-    validateCommand "$dir" "$PHP" "php" 
-    validateCommand "$dir" "$PHPMD" "php" 
-    validateCommand "$dir" "$PHPCS" "php" 
+    validateCommand "$dir" "$PHP" "php" "$PHP_OPTIONS" "> /dev/null"
+    validateCommand "$dir" "$PHPMD" "php" "" "$PHPMD_OPTIONS $PHPMD_CONFIG"
+    validateCommand "$dir" "$PHPCS" "php" "$PHPCS_OPTIONS $PHPCS_CONFIG"
     validateCommand "$dir" "$CHECKBASH" "bash" "$CHECKBASH_OPTIONS" 
     validateCommand "$dir" "$CHECKSH" "sh" "$CHECKSH_OPTIONS"
-    validateCommand "$dir" "$YAML" "yml" "$YAML_OPTIONS" " > /dev/null"
+    validateCommand "$dir" "$YAML" "yml" "$YAML_OPTIONS" "> /dev/null"
 }
 
 
@@ -1267,6 +1292,7 @@ publish()
     publishCommand "$to" "$HTML_MINIFIER" "html" "$HTML_MINIFIER_OPTIONS" "--output" 
     publishCommand "$to" "$CLEANCSS" "css" "" "-o" 
     publishCommand "$to" "$UGLIFYJS" "js" "$UGLIFYJS_OPTIONS" "-o" 
+    publishCommand "$to" "$MINIFYPHP" "php" "$MINIFYPHP_OPTIONS" ">" 
     #publishCommand "$to" "$UGLIFYPHP" "php" "" "--output" 
 
     publishChmod "$to"
