Added command to test course repos, testrepo.

diff --git a/dbwebb2 b/dbwebb2
--- a/dbwebb2
+++ b/dbwebb2
@@ -30,7 +30,7 @@
 #
 # Current version
 #
-DBW_VERSION="v1.9.39 (2016-05-13)"
+DBW_VERSION="v1.9.40 (2016-05-13)"
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -438,12 +438,17 @@ mapCmdToDir()
             esac
             ;;
 
-            oopython)
-                case "$CMD" in
-                    lab1)       RES="me/kmom01/lab1" ;;
-                    lab2)       RES="me/kmom02/lab2" ;;
-                esac
-                ;;
+        oopython)
+            case "$CMD" in
+                flask)      RES="me/kmom01/flask" ;;
+                minizoo)    RES="me/kmom02/minizoo" ;;
+                test)       RES="me/kmom02/test" ;;
+                uml)        RES="me/kmom02/uml" ;;
+
+                lab1)       RES="me/kmom01/lab1" ;;
+                lab2)       RES="me/kmom02/lab2" ;;
+            esac
+            ;;
     esac
 
     echo "$RES"
@@ -739,7 +744,7 @@ fi
 DBW_OS="$( uname -a )"
 
 # Create the ssh-command with details from the config-file
-SSH_CMD="ssh ${DBW_USER}@${DBW_HOST} $DBW_SSH_KEY_OPTION"
+SSH_CMD="ssh -n ${DBW_USER}@${DBW_HOST} $DBW_SSH_KEY_OPTION"
 
 # Default chmod for rsync-command 
 RSYNC_CHMOD="--chmod=Du+w,Dgo+rx,Fu+rw,Fgo+r"
@@ -795,6 +800,7 @@ function usage ()
 "  publishpure [part] Publish without minification."
 "  inspect [course] [kmom] [user]  Inspect a kmom."
 "  run <command>      Run a command on remote host."
+"  testrepo           Automated tests of a course repo."
 ""
 "Options:"
 "  --inspect, -i  Help for inspect."
@@ -1318,7 +1324,7 @@ function dbwebb-validate()
     local intro="Uploading the directory '$WHAT' to '$WHERE' for validation."
     local command1="$RSYNC_CMD $OVERWRITE '$WHAT' '$WHERE'"
     local command2="rsync -av $RSYNC_CHMOD $OVERWRITE --exclude .git --exclude .gitignore --exclude .default --exclude .solution --exclude .old --include='.??*' --exclude='*' -e \"ssh $DBW_SSH_KEY_OPTION\" '$DBW_COURSE_DIR/' '$DBW_REMOTE_DESTINATION/'"
-    local command3="$SSH_CMD 'dbwebb-validate --course-repo \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\" \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' 2>&1 | tee '$log';"
+    local command3="$SSH_CMD 'dbwebb-validate --course-repo \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\" \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' 2>&1 | tee '$log'; test \${PIPESTATUS[0]} -eq 0"
     local message="to validate course results.\nSaved a log of the output: less -R '$log'"
     executeCommand "$intro" "$command1; $command2; $command3" "$message"
 }
@@ -1344,7 +1350,7 @@ function dbwebb-publish()
     local intro="Uploading the directory '$WHAT' to '$WHERE' to validate and publish."
     local command1="$RSYNC_CMD $OVERWRITE '$WHAT' '$WHERE'"
     local command2="rsync -av $RSYNC_CHMOD $OVERWRITE --exclude .git --exclude .gitignore --exclude .default --exclude .solution --exclude .old --include='.??*' --exclude='*' -e \"ssh $DBW_SSH_KEY_OPTION\" '$DBW_COURSE_DIR/' '$DBW_REMOTE_DESTINATION/'"
-    local command3="$SSH_CMD 'dbwebb-validate $PUBLISH_OPTIONS --publish --course-repo \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\" --publish-to \"$DBW_REMOTE_WWWDIR/$DBW_COURSE/$SUBDIR\" \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' 2>&1 | tee '$log';"
+    local command3="$SSH_CMD 'dbwebb-validate $PUBLISH_OPTIONS --publish --course-repo \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\" --publish-to \"$DBW_REMOTE_WWWDIR/$DBW_COURSE/$SUBDIR\" \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' 2>&1 | tee '$log'; test \${PIPESTATUS[0]} -eq 0"
     local message="to validate and publish course results.\nSaved a log of the output: less -R '$log'"
     executeCommand "$intro" "$command1; $command2; $command3" "$message"
 
@@ -1465,7 +1471,7 @@ function dbwebb-inspect()
     local intro="I will now inspect '$kmom'${forCourse}${forWho}.$willUpload"
     local log="$HOME/.dbwebb-inspect.log"
     local command1=
-    local command2="$SSH_CMD \"dbwebb-inspect $archive --publish-url $DBW_BASEURL --publish-to ~$DBW_USER/$DBW_REMOTE_WWWDIR --base-url $DBW_WWW_HOST~$inspecUser/$DBW_REMOTE_BASEDIR ~$inspecUser/$DBW_REMOTE_BASEDIR/$course $kmom\" 2>&1 | tee '$log';"
+    local command2="$SSH_CMD \"dbwebb-inspect $archive --publish-url $DBW_BASEURL --publish-to ~$DBW_USER/$DBW_REMOTE_WWWDIR --base-url $DBW_WWW_HOST~$inspecUser/$DBW_REMOTE_BASEDIR ~$inspecUser/$DBW_REMOTE_BASEDIR/$course $kmom\" 2>&1 | tee '$log'; test \${PIPESTATUS[0]} -eq 0"
     local message="to inspect the course results.\nSaved a log of the output, review it as:\nless -R '$log'"
 
     # Upload only if
@@ -1645,6 +1651,74 @@ dbwebb-updateconfig()
 
 
 
+#
+# Support testing procedure of course repo
+#
+dbwebb-testrepo()
+{
+    checkIfValidConfigOrExit
+    checkIfValidCourseRepoOrExit
+
+    local base="$DBW_COURSE_DIR"
+    local me="$base/me"
+    local testsuite="$base/.dbwebb.tests"
+    local prompt="==="
+    local silent=
+
+    if [ ! -f "$testsuite" ]; then
+        printf "$MSG_FAILED There is no testsuite file '.dbwebb.tests' in this course repo. This courese repo does not (yet) support automated tests.\n"
+        exit 2
+    fi
+
+    if [ -d "$me" -a -z "$OVERWRITE" ]; then
+        printf "$MSG_FAILED The me-directory is already here. You can not run tests with an existing me-directory. Remove the me-directory so it can be recreated by the test procedure.\n"
+        exit 2
+    fi
+
+    if [[ $SILENT ]]; then
+        silent=" > /dev/null"
+    fi
+
+    echo "$prompt Beginning testsuite"
+    cd "$base"
+
+    local lineNum=0
+    local assertions=0
+    local fail=0
+    
+    while IFS= read -r line
+    do
+        ((lineNum++))
+        printf "$prompt $lineNum: $line\n"
+
+        if [ -z "$line" -o "${line:0:1}" == "#" ]; then
+            continue;
+        fi
+        
+        if [[ $SILENT ]]; then
+            line=$( echo "$line" | sed 's/;/ > \/dev\/null;/' )
+        fi
+
+        ((assertions++))
+        ( bash -c "$line $silent" )
+        if [ $? != 0 ]; then
+            printf "$prompt $lineNum: $MSG_FAILED\n"
+            ((fail++))
+        fi
+
+    done < <(grep "" "$testsuite")
+
+    echo "$prompt Done with $assertions assertions and $fail failure(s)."
+    if [[ $fail = 0 ]]; then
+        printf "$prompt $MSG_OK All tests passed.\n"
+    else 
+        printf "$prompt $MSG_FAILED $fail assertion(s) failed.\n"
+        exit 1
+    fi
+}
+
+
+
 # --------------- DBWEBB MAIN START HERE ------------------------------
 #
 # Process options
@@ -1722,6 +1796,7 @@ do
         | run          \
         | create       \
         | recreate     \
+        | testrepo     \
         | init         \
         | init-server  \
         | init-structure-dbwebb-kurser \
@@ -1730,7 +1805,7 @@ do
             command=$1
             shift
             dbwebb-$command $*
-            exit 0
+            exit
         ;;
         
         *)
