Inspect for oopython kmom04. Inspect for linux kmom04.

diff --git a/dbwebb2-inspect b/dbwebb2-inspect
--- a/dbwebb2-inspect
+++ b/dbwebb2-inspect
@@ -30,7 +30,7 @@
 #
 # Current version
 #
-DBW_VERSION="v1.9.71 (2017-01-30)"
+DBW_VERSION="v1.9.73 (2017-02-03)"
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -982,6 +982,7 @@ function usage ()
 "  --help, -h             Print help."
 "  --version, -v          Print version."
 "  --yes, -y              Answer yes/default to all answers."
+"  --port port, -p port   Execute external servers on this port."
 "  --useVersion id, -u id Use specific version of course."
 "  --archive path         Path where the archive is."
 "  --config path          Path to config file to source."
@@ -1928,7 +1929,13 @@ function oopythonkmom03()
 #
 function oopythonkmom04()
 {
-    :
+    inspectLab "uppgift/python-med-regex" "lab3" "answer.py" "python3 answer.py"
+
+    inspectExerciseHeader "Skapa en bondgårdssdatabas" "uppgift/skapa-en-bondgards-databas" "flask"
+    executeSQLite "me/flask/db/farms.sqlite" ".schema"
+
+    inspectExerciseHeader "Visa bondgården på me-sidan" "uppgift/visa-bondgarden-pa-me-sida" "flask"
+    printUrl "" "me/flask"
 }
 
 
@@ -2412,19 +2419,29 @@ function linuxkmom03()
 #
 function linuxkmom04()
 {
-    inspectExercise "javascripting" "uppgift/utfor-nodeschool-workshopen-javascripting" "" "" "" "" "" ""
+    if [ "$USE_VERSION" = "1" ]; then
+        inspectExercise "javascripting" "uppgift/utfor-nodeschool-workshopen-javascripting" "" "" "" "" "" ""
 
-    inspectExercise "server" "uppgift/skapa-en-restful-http-server-med-node-js-och-klient-i-bash" "index.js" "server.js" "" "" "" "" "" "" " (del 1 servern)"
+        inspectExercise "server" "uppgift/skapa-en-restful-http-server-med-node-js-och-klient-i-bash" "index.js" "server.js" "" "" "" "" "" "" " (del 1 servern)"
 
-    inspectExercise "server" "uppgift/skapa-en-restful-http-server-med-node-js-och-klient-i-bash" "client.bash" "" "" "" "" "" "" "" " (del 2 klienten)"
+        inspectExercise "server" "uppgift/skapa-en-restful-http-server-med-node-js-och-klient-i-bash" "client.bash" "" "" "" "" "" "" "" " (del 2 klienten)"
 
-    export LINUX_SERVER="127.0.0.1"
-    if [[ ! ${LINUX_PORT+x} ]]; then 
-        export LINUX_PORT="1337"
+        return
     fi
-    
+
+    inspectLab "uppgift/linux-lab3-introduktion-till-nodejs" "node1" "answer.js" "babel-node answer.js"
+
+    # Prepare
+    inspectExerciseHeader "Server i node och klient i bash" "uppgift/skapa-en-restful-http-server-med-node-js-och-klient-i-bash" "$KMOM/server"
+
+    # Start the server
     local target="me/$KMOM/server"
+    fileIsReadable "me/$KMOM/server/index.js"
+    fileIsReadable "me/$KMOM/server/server.js"
     runServer "index.js" "$THEDIR/$target" "babel-node index.js"
+
+    # Execute the client
+    fileIsReadable "me/$KMOM/server/client.bash"
     inspectCommand "client.bash" "$THEDIR/$target" "bash client.bash hello"
     inspectCommand "client.bash" "$THEDIR/$target" "bash client.bash html"
     inspectCommand "client.bash" "$THEDIR/$target" "bash client.bash status"
@@ -2432,6 +2449,8 @@ function linuxkmom04()
     inspectCommand "client.bash" "$THEDIR/$target" "bash client.bash filter 2 3 42 99"
     inspectCommand "client.bash" "$THEDIR/$target" "bash client.bash 404"
     inspectCommand "client.bash" "$THEDIR/$target" "bash client.bash all"
+
+    # Close it up
     killServer
 }
 
@@ -2816,6 +2835,33 @@ printUrl()
 #
 # Check if file exists and display it 
 #
+executeSQLite()
+{
+    local file="$1"
+    localdir="$THEDIR"
+    local sql="$2"
+
+    assert 0 "test -f \"$THEDIR/$file\"" "The file '$file' is missing or not readable."
+
+    if [ $? -eq 0 ]; then
+        printf "\nSQLite '%s':\nView '%s' [Yn]? " "$file" "$sql"
+
+        local answer=$( answerYesOrNo "y" )
+        if [ "$answer" = "y" -o "$answer" = "Y" ]
+        then
+            echo ">>>"
+            sqlite3 --header --column "$dir/$file" "$sql"
+            echo "<<<"
+            pressEnterToContinue
+        fi
+    fi
+}
+
+
+
+#
+# Check if file exists and display it 
+#
 viewFileContent()
 {
     local file="$1"
@@ -3179,6 +3225,18 @@ inspectCommand()
 
 
 #
+# Set default settings for running server
+#
+serverSettings()
+{
+    LINUX_PORT=${LINUX_PORT:-1342}
+    export LINUX_PORT=${PORT:-$LINUX_PORT}
+    export LINUX_SERVER=${LINUX_SERVER:-127.0.0.1}
+}
+
+
+
+#
 # Execute a command as a server in the background logging output to a file.
 #
 runServer()
@@ -3191,29 +3249,34 @@ runServer()
     local filename="$move/$what"
     
     local logfile=".serverlog.txt"
-    SERVER_LOG="$move/$logfile"
+    export SERVER_LOG="$move/$logfile"
 
     if [ ! -z "$what" ]; then
         assert 0 "test -f \"$filename\" -o -r \"$filename\"" "The file '$what' is missing or not readable."
     fi
     
     if [ $? == 0 ]; then
-        printf "\nExecute '%s' as server and log its output to '$logfile' [Yn]? " "$cmd"
+        serverSettings
+
+        printf "\nExecute '%s' as server on $LINUX_SERVER:$LINUX_PORT and log its output to '$logfile' [Yn]? " "$cmd"
 
         local answer=$( answerYesOrNo "y" )
         if [ "$answer" = "y" -o "$answer" = "Y" ]; then
 
+            [[ -f pid ]] && rm pid
             pushd "$move" > /dev/null
             echo ">>>"
-            $cmd > "$SERVER_LOG" &
+            $cmd &> $SERVER_LOG &
             status=$?
             SERVER_PID=$!
-            echo "$cmd started with pid $SERVER_PID."
-            echo "Will kill server automatically within 60 seconds."
-            sleep 60 && kill $SERVER_PID &
-            echo "Sleeping 3 before continuing."
+            echo "$cmd started with pid '$SERVER_PID' and status $status (sleeping 3 before continue)..."
             sleep 3
+            echo "(Will kill server automatically within 60 seconds.)"
+            [[ -f pid ]] || printf "$MSG_WARNING Missing pid file!\n"
+            local pid=$( [[ -f pid ]] && cat pid )
+            echo "File pid contains: '$pid'"
             echo "<<<"
+            sleep 60 && kill $SERVER_PID $id &> /dev/null &
             popd > /dev/null
 
             if [ $status -eq 0 ]; then
@@ -3234,14 +3297,18 @@ runServer()
 #
 killServer()
 {
-    echo "Killing server."
+    local PID=$( cat pid )
+
+    echo
     echo ">>>"
-    kill $SERVER_PID
-    echo "Sent kill signal to server."
-    echo "Sleeping 3 before continuing."
+    echo "Killing server with PID $PID (sleeping 3 before continue)..."
+    kill $PID &> /dev/null
     sleep 3
+    kill $SERVER_PID &> /dev/null # To be sure then file pid is missing
     echo "Printing logfile from server:"
+    echo "--------- Logfile start  ---------"
     cat "$SERVER_LOG"
+    echo "--------- Logfile end    ---------"
     echo "<<<"
 }
 
@@ -3271,6 +3338,12 @@ do
 
         --yes | -y)
             YES="yes"
+            shift
+        ;;
+
+        --port | -p)
+            PORT="$2"
+            shift
             shift
         ;;
 
