enabling publish

diff --git a/dbwebb2-validate b/dbwebb2-validate
--- a/dbwebb2-validate
+++ b/dbwebb2-validate
@@ -247,6 +247,20 @@ function checkIfValidCourseRepoOrExit()
 
 
 #
+# Check if config file or exit
+#
+function checkIfValidConfigOrExit()
+{
+    if [ ! -f "$DBW_CONFIG_FILE" ]; then
+        printf "$MSG_FAILED Could not find the configuration file '$DBW_CONFIG_FILE', this is needed for this operation."
+        printf "\n"
+        exit 1
+    fi
+}
+
+
+
+#
 # Set proper rights for files and directories
 #
 setChmod()
@@ -503,6 +517,7 @@ function dbwebb-init-server()
     local command="$SSH_CMD 'sh -c \"if [ ! -d \"$DBW_REMOTE_BASEDIR\" ]; then mkdir \"$DBW_REMOTE_BASEDIR\"; fi; chmod 700 \"$DBW_REMOTE_BASEDIR\"; echo; echo \"$DBW_REMOTE_BASEDIR:\"; ls -lF \"$DBW_REMOTE_BASEDIR\"; if [ ! -d \"$DBW_REMOTE_WWWDIR\" ]; then mkdir \"$DBW_REMOTE_WWWDIR\"; fi; chmod 755 \"$DBW_REMOTE_WWWDIR\"; echo; echo \"$DBW_REMOTE_WWWDIR:\"; ls -lF \"$DBW_REMOTE_WWWDIR\"\"'"
     local message="to init the server."
 
+    checkIfValidConfigOrExit
     executeCommand "$intro" "$command" "$message"
 }
 
@@ -562,6 +577,7 @@ function dbwebb-login()
     local command="$SSH_CMD"
     local message="to establish the connection."
     
+    checkIfValidConfigOrExit
     executeCommand "$intro" "$command" "$message"
 }
 
@@ -650,6 +666,7 @@ function dbwebb-upload()
     ITEM="$1"
     SUBDIR=""
 
+    checkIfValidConfigOrExit
     checkIfValidCourseRepoOrExit
     createUploadDownloadPaths
     setChmod
@@ -672,6 +689,7 @@ function dbwebb-download()
     ITEM="$1"
     SUBDIR=""
 
+    checkIfValidConfigOrExit
     checkIfValidCourseRepoOrExit
     createUploadDownloadPaths
 
@@ -693,6 +711,7 @@ function dbwebb-validate()
     ITEM="$1"
     SUBDIR=""
 
+    checkIfValidConfigOrExit
     checkIfValidCourseRepoOrExit
     createUploadDownloadPaths
     setChmod
@@ -700,7 +719,8 @@ function dbwebb-validate()
     local log="$HOME/.dbwebb-validate.log"
     local intro="Uploading the directory '$WHAT' to '$WHERE' for validation."
     local command1="$RSYNC_CMD '$WHAT' '$WHERE'"
-    local command2="$SSH_CMD 'cd \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\"; dbwebb-validate \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' | tee '$log';"
+    #local command2="$SSH_CMD 'cd \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\"; dbwebb-validate \"$SUBDIR\"' | tee '$log';"
+    local command2="$SSH_CMD 'dbwebb-validate --course-repo \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\" \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' | tee '$log';"
     local message="to validate course results.\nSaved a log of the output: less -R '$log'"
     executeCommand "$intro" "$command1; $command2" "$message"
 }
@@ -717,6 +737,7 @@ function dbwebb-publish()
     ITEM="$1"
     SUBDIR=""
 
+    checkIfValidConfigOrExit
     checkIfValidCourseRepoOrExit
     createUploadDownloadPaths
     setChmod
@@ -724,7 +745,7 @@ function dbwebb-publish()
     local log="$HOME/.dbwebb-publish.log"
     local intro="Uploading the directory '$WHAT' to '$WHERE' to validate and publish."
     local command1="$RSYNC_CMD '$WHAT' '$WHERE'"
-    local command2="$SSH_CMD 'dbwebb-validate --publish --publish-to \"$DBW_REMOTE_WWWDIR/$DBW_COURSE/$SUBDIR\" \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' | tee '$log';"
+    local command2="$SSH_CMD 'dbwebb-validate --publish --course-repo \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\" --publish-to \"$DBW_REMOTE_WWWDIR/$DBW_COURSE/$SUBDIR\" \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' | tee '$log';"
     local message="to validate and publish course results.\nSaved a log of the output: less -R '$log'"
     executeCommand "$intro" "$command1; $command2" "$message"
 
@@ -752,6 +773,7 @@ dbwebb-create()
         exit 2
     fi
 
+    checkIfValidConfigOrExit
     checkIfValidCourseRepoOrExit
 
     printf "Creating $DBW_COURSE $lab in '$where'.\n"
@@ -959,28 +981,28 @@ done
 
 
 
+#
 # Get the name of the course as $DBW_COURSE
-DBW_COURSE_FILE="$DBW_COURSE_DIR/$DBW_COURSE_FILE_NAME"
-DBW_COURSE_REPO_VALID=""
-if [ -f "$DBW_COURSE_FILE" ]; then
-    DBW_COURSE_REPO_VALID="yes"
-    source "$DBW_COURSE_FILE"
-fi
+#
+function sourceCourseRepoFile()
+{
+    DBW_COURSE_FILE="$DBW_COURSE_DIR/$DBW_COURSE_FILE_NAME"
+    DBW_COURSE_REPO_VALID=""
+    if [ -f "$DBW_COURSE_FILE" ]; then
+        DBW_COURSE_REPO_VALID="yes"
+        source "$DBW_COURSE_FILE"
+    fi    
+}
+
+# Get the name of the course as $DBW_COURSE
+sourceCourseRepoFile
 
 
 
 # Where is the .dbwebb.config-file
-DBW_CONFIG_DEFAULT_FILE="$DBW_INSTALL_DIR/dbwebb2-config-sample"
 DBW_CONFIG_FILE_NAME=".dbwebb.config"
 DBW_CONFIG_FILE="$HOME/$DBW_CONFIG_FILE_NAME"
-if [ ! -f "$DBW_CONFIG_FILE" ]; then
-
-    # If the command is to init-repo, then execute that and create a config-file
-    if [ "$1" = "init-repo" ]; then
-        createConfig
-        exit 0
-    fi
-else
+if [ -f "$DBW_CONFIG_FILE" ]; then
     source "$DBW_CONFIG_FILE"
 fi
 
@@ -1323,6 +1345,20 @@ do
                 badUsage "$MSG_FAILED --publish-to '$DBW_PUBLISH_TO' is not a valid directory."
                 exit 2
             fi
+                
+            shift
+            shift
+            ;;
+
+        --course-repo)
+            DBW_COURSE_DIR="$2"
+            if [ ! -d "$DBW_COURSE_DIR" ) ]; then
+                badUsage "$MSG_FAILED --course-repo '$DBW_COURSE_DIR' is not a valid directory."
+                exit 2
+            fi
+
+            # Get the name of the course as $DBW_COURSE
+            sourceCourseRepoFile
                 
             shift
             shift
