rewriting for dbwebb2

diff --git a/dbwebb2 b/dbwebb2
--- a/dbwebb2
+++ b/dbwebb2
@@ -1,3 +1,101 @@
+#!/bin/bash
+# dbwebb: tool to manage course repos
+#
+# The MIT License (MIT)
+#
+# Copyright (c) 2014-2015 Mikael Roos (me@mikaelroos.se)
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in
+# all copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
+DBW_VERSION="1.1.1"
+mapfile usage <<EOD
+Utility dbwebb version $DBW_VERSION by Mikael Roos (mos@dbwebb.se), to work with dbwebb course repositories.
+
+Usage: dbwebb [options] <command> [arguments]
+
+Command:
+
+  check             Check and print out details on the environment.
+  config            Create, or re-create the config file.
+  selfupdate        Update dbwebb-cli installation.
+  sshkey            Create and install ssh-keys to avoid using password.
+  login             Login to the remote server using ssh and sshkeys if available.
+  init-server       Init the server by creating a directory structure on it.
+
+Command (to manage course repos):
+
+  ls                List all locally installed course repos within \$DBW_HOME.
+  repo              List all supporoted remote course repos.
+  clone repo-name   Clone and locally install a remote course repo.
+
+Command (for a valid course repo):
+
+  init-me           Init the directory me/ by copying files and directories from default/.
+  update            Update the courserepo with latest updates from the master repo.
+  upload [part]     Upload current directory to the the server.
+  download [part]   Download current directory from the server (overwrite all files, be careful).
+  create labid      Create a laboration, use additional argument for naming what lab to create.
+  validate [part]   Validate (and upload) your files using the remote server.
+  publish [part]    Upload, Validate and Publish your course results to the web.
+  inspect kmom [user]   Inspect a kmom for yourself or a specific user, needs teacher privilegies
+                        to check another students kmom.
+
+Options:
+
+  -i, --inspect  Prints help with commands for inspect.
+  -v, --verbose  Verbose, print out what's happening.
+  -y, --yes      Do not wait for my input, just proceed.
+  -h, --help     Print this message and exit.
+  --version      Print version and exit.
+  
+EOD
+
+
+
+mapfile version <<EOD
+dbwebb version $DBW_VERSION
+
+EOD
+
+
+
+mapfile badUsage <<EOD
+For an overview of the command, execute:
+dbwebb --help
+
+EOD
+
+
+
+mapfile inspectUsage <<EOD
+Commands useful at the server with respect to dbwebb inspect, needs extra privilegies.
+
+Open up for inspect by setting group and chmod for directories and files.
+sudo /usr/local/sbin/setpre-dbwebb-kurser.bash acronym
+
+Add or delete as member of the dbwebb-group (execute on all servers)
+sudo update-dbwebb-kurser.bash -a acronym
+sudo update-dbwebb-kurser.bash -d acronym
+
+Execute command as the user dbwebb.
+sudo -u dbwebb script
+
+EOD
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -408,6 +506,28 @@ createUploadDownloadPaths()
 
 
 #
+# Validate the uploaded files
+#
+validateUploadedResults()
+{
+    WHAT="$1"
+    WHERE="$2"
+    ITEM="$3"
+    SUBDIR=""
+
+    createUploadDownloadPaths
+
+    local LOG="$HOME/.dbwebb-validate.log"
+    local INTRO="I will now upload files to the remote server and validate them."
+    local COMMAND1="$RSYNC_CMD '$WHAT' '$WHERE'"
+    local COMMAND2="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; dbwebb-validate -n $IGNORE_FAULTS $WHAT' | tee '$LOG';"
+    local MESSAGE="to validate course results. Saved a log of the output, review it as:\nless -R '$LOG'"
+    executeCommand "$INTRO" "$COMMAND1; $COMMAND2" "$MESSAGE"
+}
+
+
+
+#
 # Validate and Publish the uploaded files
 #
 publishResults()
@@ -780,27 +900,281 @@ function dbwebb-download()
 
 
 
-#
-# Validate the uploaded files
-#
-function dbwebb-validate()
-{
-    WHAT="$1"
-    WHERE="$2"
-    ITEM="$3"
-    SUBDIR=""
-
-    createUploadDownloadPaths
-    setChmod
-
-    local LOG="$HOME/.dbwebb-validate.log"
-    local INTRO="I will now upload files to the remote server and validate them."
-    local COMMAND1="$RSYNC_CMD '$WHAT' '$WHERE'"
-    local COMMAND2="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; dbwebb-validate -n $IGNORE_FAULTS $WHAT' | tee '$LOG';"
-    local MESSAGE="to validate course results. Saved a log of the output, review it as:\nless -R '$LOG'"
-    executeCommand "$INTRO" "$COMMAND1; $COMMAND2" "$MESSAGE"
-}
-
-
-
 # --------------- DBWEBB FUNCTIONS PHASE END ---------------
+# --------------- DBWEBB BOOTSTRAP PHASE START ---------------
+
+#
+# Specify the utilities used
+#
+ECHO="printf"
+GIT="git"
+RSYNC="rsync"
+SSH="ssh"
+SED="sed"
+WGET="wget"
+CURL="curl"
+BASH="bash"
+FIND="find"
+
+
+# Revise these
+UPLOAD="$RSYNC -av --delete --exclude literature --exclude .git -e \"ssh $DBW_SSH_KEY_OPTION\" \"$SOURCE\" \"$DESTINATION\""
+UPLOAD_MINIMAL="$RSYNC -av --delete --exclude me --exclude tutorial --exclude example --exclude literature --exclude .git -e \"ssh $DBW_SSH_KEY_OPTION\" \"$SOURCE\" \"$DESTINATION\""
+
+
+# Settins
+MSG_OK="\033[0;30;42mOK\033[0m"
+MSG_WARNING="\033[43mWARNING\033[0m"
+MSG_FAILED="\033[0;37;41mFAILED\033[0m"
+
+
+# For asserts
+ASSERTS=0
+FAULTS=0
+TMPFILE="/tmp/dbwebb-error-{$USER}-$$"
+
+
+
+#
+# Find my environment, before any work can be done
+#
+
+
+# What was the command issued?
+DBW_EXECUTABLE="$( basename "$0" )"
+
+# Where is the executable
+DBW_EXECUTABLE_DIR="$( dirname "$0" )"
+
+# Where is the installation directory
+#DBW_CLIDIR="dbwebb-cli"
+#DBW_VERSION_FILE_NAME=".dbwebb.version"
+
+#if [ -f "$DBW_EXECUTABLE_DIR/$DBW_VERSION_FILE_NAME" ]; then
+#    DBW_INSTALL_DIR="$DBW_EXECUTABLE_DIR"
+#elif [ -d "$DBWEBB_HOME" -a -d "$DBWEBB_HOME/$DBW_CLIDIR" ]; then
+#    DBW_INSTALL_DIR="$DBWEBB_HOME/$DBW_CLIDIR"
+#elif [ -d "$DBWEBB_CLI_HOME" ]; then
+#    DBW_INSTALL_DIR="$DBWEBB_CLI_HOME"
+#elif [ -d "$HOME/$DBW_BASEDIR/$DBW_CLIDIR" ]; then
+#    DBW_INSTALL_DIR="$HOME/$DBW_BASEDIR/$DBW_CLIDIR"
+#else 
+#    $ECHO "$MSG_FAILED Could not determine the installation directory. I tried tried the environment variables \$DBWEBB_HOME and \$DBWEBB_CLI_HOME and looked in \$HOME/$DBW_BASEDIR/$DBW_CLIDIR.\n"
+#    exit 1
+#fi
+
+
+
+# Get the current version installed as $DBW_VERSION
+#DBW_VERSION_FILE="$DBW_INSTALL_DIR/$DBW_VERSION_FILE_NAME"
+#if [ ! -f "$DBW_VERSION_FILE" ]; then
+#    $ECHO "$MSG_FAILED Missing file $DBW_VERSION_FILE_NAME. The installation directory does not contain a valid installation.\n"
+#    exit 1
+#fi
+#source "$DBW_VERSION_FILE"
+
+
+
+# What is the current directory
+DBW_CURRENT_DIR="$( pwd )"
+
+
+
+# What is the directory of the current course repo, find recursivly up the tree
+DBW_COURSE_FILE_NAME=".dbwebb.course"
+
+dir="$DBW_CURRENT_DIR/."
+while [ "$dir" != "/" ]; do 
+    dir=$( dirname "$dir" )
+    found="$( find "$dir" -maxdepth 1 -name $DBW_COURSE_FILE_NAME )"
+    if [ "$found" ]; then 
+        DBW_COURSE_DIR="$( dirname $found )"
+        break
+    fi
+done
+
+
+
+# Where is the directory for the course repos, if any
+DBW_BASEDIR="dbwebb-kurser"
+if [ -d "$DBWEBB_HOME" ]; then
+    DBW_HOME="$DBW_BASEDIR"
+elif [ -d "$HOME/$DBW_BASEDIR" ]; then
+    DBW_HOME="$HOME/$DBW_BASEDIR"
+fi
+
+
+
+# Get the name of the course as $DBW_COURSE
+DBW_COURSE_FILE="$DBW_COURSE_DIR/$DBW_COURSE_FILE_NAME"
+DBW_COURSE_REPO_VALID=""
+if [ -f "$DBW_COURSE_FILE" ]; then
+    DBW_COURSE_REPO_VALID="yes"
+    source "$DBW_COURSE_FILE"
+fi
+
+
+
+# Where is the .dbwebb.config-file
+DBW_CONFIG_DEFAULT_FILE="$DBW_INSTALL_DIR/dbwebb2-config-sample"
+DBW_CONFIG_FILE_NAME=".dbwebb.config"
+DBW_CONFIG_FILE="$HOME/$DBW_CONFIG_FILE_NAME"
+if [ ! -f "$DBW_CONFIG_FILE" ]; then
+
+    # If the command is to init-repo, then execute that and create a config-file
+    if [ "$1" = "init-repo" ]; then
+        createConfig
+        exit 0
+    fi
+else
+    source "$DBW_CONFIG_FILE"
+fi
+
+# Name the remote server
+DBW_HOST="ssh.student.bth.se"
+
+# Check OS
+DBW_OS="$( uname -a )"
+
+# Create the ssh-command with details from the config-file
+SSH_CMD="$SSH ${DBW_USER}@${DBW_HOST} $DBW_SSH_KEY_OPTION"
+
+# Create the basis for the upload command
+RSYNC_CMD="$RSYNC -av --delete --exclude .git --exclude .gitignore -e \"ssh $DBW_SSH_KEY_OPTION\""
+RSYNC_DOWNLOAD_CMD="$RSYNC -avu -e \"ssh $DBW_SSH_KEY_OPTION\""
+
+DBW_REMOTE_DESTINATION="${DBW_USER}@${DBW_HOST}:$DBW_BASEDIR/$DBW_COURSE"
+
+
+
+# --------------- DBWEBB BOOTSTRAP PHASE END ---------------
+# --------------- DBWEBB MAIN START HERE ---------------
+
+#
+# TODO Check how config-file is initiated
+# Check if config file is up to date
+#
+updateConfigIfNeeded "update"
+
+
+
+#
+# TODO CLEAN UP THESE
+# Get options
+#
+SKIP_READLINE="no"
+IGNORE_FAULTS="-i"
+VERY_VERBOSE="no"
+
+
+
+#
+# Process options
+#
+while (( $# ))
+do
+    case "$1" in
+        
+        --inspect | -i)
+            printf %s "${inspectUsage[@]}"
+            exit 0
+        ;;
+
+        --verbose | -v)
+            VERY_VERBOSE="yes"
+        ;;
+
+        --yes | -y)
+            SKIP_READLINE="yes"
+        ;;
+
+        --help | -h)
+            printf %s "${usage[@]}"
+            exit 0
+        ;;
+        
+        --version)
+            printf %s "${version[@]}"
+            exit 0
+        ;;
+                
+        clone)
+            if [ -z "$2" ]; then
+                $ECHO "\n$MSG_FAILED missing argument for repo name."
+                $ECHO "\n"
+                dbwebb2PrintShortUsage
+                exit 1
+            fi
+            reposClone "$2"
+            exit 0
+        ;;
+
+        selfupdate|self-update)
+            selfUpdate
+            exit 0
+        ;;
+
+#    init)
+#        initServer
+#        createDefaultFiles
+#        #uploadToServer
+#        ;;
+
+        create)
+            LAB="$2"
+            if [ -z "$LAB" ]
+            then
+                echo "Missing name for lab, perhaps use lab1, lab2 or lab3?"
+                exit 1
+            fi
+            createLab "$LAB"
+            exit 0
+        ;;
+
+        validate)
+            setChmod
+            validateUploadedResults "$DBW_COURSE_DIR" "$DBW_REMOTE_DESTINATION" "$2"
+            exit 0
+        ;;
+
+        publish)
+            setChmod
+            publishResults "$DBW_COURSE_DIR" "$DBW_REMOTE_DESTINATION" "$2"
+            exit 0
+        ;;
+
+        inspect)
+            WHICH=$2
+            WHO=$3
+            inspectResults ${WHICH:=all} ${WHO:=$USER}
+            exit 0
+        ;;
+
+        update        \
+        | check       \
+        | config      \
+        | ls          \
+        | repo        \
+        | sshkey      \
+        | login       \
+        | upload      \
+        | download    \
+        | init-server \
+        | init-me)
+            command=$1
+            shift
+            dbwebb-$command $*
+            exit 0
+        ;;
+        
+        *)
+            printf "$MSG_FAILED Option/command not recognized.\n\n"
+            printf %s "${badUsage[@]}"
+            exit 1
+        ;;
+        
+    esac
+done
+
+printf %s "${badUsage[@]}"
+exit 1
diff --git a/dbwebb2-validate b/dbwebb2-validate
--- a/dbwebb2-validate
+++ b/dbwebb2-validate
@@ -1,3 +1,65 @@
+#!/bin/bash
+# dbwebb-validate: tool to validate and publish course repos
+#
+# The MIT License (MIT)
+#
+# Copyright (c) 2014-2015 Mikael Roos (me@mikaelroos.se)
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in
+# all copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
+DBW_VERSION="1.1.1"
+mapfile usage <<EOD
+Utility dbwebb-validate version $DBW_VERSION by Mikael Roos (mos@dbwebb.se), to work with dbwebb course repositories.
+
+Usage: dbwebb-validate [options] [item]
+
+Item:
+
+  Any of the supporter exercises for each course, for example:
+  - kmom01, kmom02, kmom03, kmom04, kmom05, kmom06, kmom10
+  - me, tutorial, example
+  or a relative path,
+  or a absolute path
+
+Options:
+
+  -c, --check    Check environment for installed tools.
+  -p, --publish  Publish, otherwise only validate.
+  -s, --silent   Silent, limited output.
+  -h, --help     Print this message and exit.
+  -v, --version  Print version and exit.
+  
+EOD
+
+
+
+mapfile version <<EOD
+dbwebb-validate version $DBW_VERSION
+
+EOD
+
+
+
+mapfile badUsage <<EOD
+For an overview of the command, execute:
+dbwebb-validate --help
+
+EOD
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -408,6 +470,28 @@ createUploadDownloadPaths()
 
 
 #
+# Validate the uploaded files
+#
+validateUploadedResults()
+{
+    WHAT="$1"
+    WHERE="$2"
+    ITEM="$3"
+    SUBDIR=""
+
+    createUploadDownloadPaths
+
+    local LOG="$HOME/.dbwebb-validate.log"
+    local INTRO="I will now upload files to the remote server and validate them."
+    local COMMAND1="$RSYNC_CMD '$WHAT' '$WHERE'"
+    local COMMAND2="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; dbwebb-validate -n $IGNORE_FAULTS $WHAT' | tee '$LOG';"
+    local MESSAGE="to validate course results. Saved a log of the output, review it as:\nless -R '$LOG'"
+    executeCommand "$INTRO" "$COMMAND1; $COMMAND2" "$MESSAGE"
+}
+
+
+
+#
 # Validate and Publish the uploaded files
 #
 publishResults()
@@ -780,27 +864,506 @@ function dbwebb-download()
 
 
 
+# --------------- DBWEBB FUNCTIONS PHASE END ---------------
+# --------------- DBWEBB BOOTSTRAP PHASE START ---------------
+
 #
-# Validate the uploaded files
+# Specify the utilities used
 #
-function dbwebb-validate()
+ECHO="printf"
+GIT="git"
+RSYNC="rsync"
+SSH="ssh"
+SED="sed"
+WGET="wget"
+CURL="curl"
+BASH="bash"
+FIND="find"
+
+
+# Revise these
+UPLOAD="$RSYNC -av --delete --exclude literature --exclude .git -e \"ssh $DBW_SSH_KEY_OPTION\" \"$SOURCE\" \"$DESTINATION\""
+UPLOAD_MINIMAL="$RSYNC -av --delete --exclude me --exclude tutorial --exclude example --exclude literature --exclude .git -e \"ssh $DBW_SSH_KEY_OPTION\" \"$SOURCE\" \"$DESTINATION\""
+
+
+# Settins
+MSG_OK="\033[0;30;42mOK\033[0m"
+MSG_WARNING="\033[43mWARNING\033[0m"
+MSG_FAILED="\033[0;37;41mFAILED\033[0m"
+
+
+# For asserts
+ASSERTS=0
+FAULTS=0
+TMPFILE="/tmp/dbwebb-error-{$USER}-$$"
+
+
+
+#
+# Find my environment, before any work can be done
+#
+
+
+# What was the command issued?
+DBW_EXECUTABLE="$( basename "$0" )"
+
+# Where is the executable
+DBW_EXECUTABLE_DIR="$( dirname "$0" )"
+
+# Where is the installation directory
+#DBW_CLIDIR="dbwebb-cli"
+#DBW_VERSION_FILE_NAME=".dbwebb.version"
+
+#if [ -f "$DBW_EXECUTABLE_DIR/$DBW_VERSION_FILE_NAME" ]; then
+#    DBW_INSTALL_DIR="$DBW_EXECUTABLE_DIR"
+#elif [ -d "$DBWEBB_HOME" -a -d "$DBWEBB_HOME/$DBW_CLIDIR" ]; then
+#    DBW_INSTALL_DIR="$DBWEBB_HOME/$DBW_CLIDIR"
+#elif [ -d "$DBWEBB_CLI_HOME" ]; then
+#    DBW_INSTALL_DIR="$DBWEBB_CLI_HOME"
+#elif [ -d "$HOME/$DBW_BASEDIR/$DBW_CLIDIR" ]; then
+#    DBW_INSTALL_DIR="$HOME/$DBW_BASEDIR/$DBW_CLIDIR"
+#else 
+#    $ECHO "$MSG_FAILED Could not determine the installation directory. I tried tried the environment variables \$DBWEBB_HOME and \$DBWEBB_CLI_HOME and looked in \$HOME/$DBW_BASEDIR/$DBW_CLIDIR.\n"
+#    exit 1
+#fi
+
+
+
+# Get the current version installed as $DBW_VERSION
+#DBW_VERSION_FILE="$DBW_INSTALL_DIR/$DBW_VERSION_FILE_NAME"
+#if [ ! -f "$DBW_VERSION_FILE" ]; then
+#    $ECHO "$MSG_FAILED Missing file $DBW_VERSION_FILE_NAME. The installation directory does not contain a valid installation.\n"
+#    exit 1
+#fi
+#source "$DBW_VERSION_FILE"
+
+
+
+# What is the current directory
+DBW_CURRENT_DIR="$( pwd )"
+
+
+
+# What is the directory of the current course repo, find recursivly up the tree
+DBW_COURSE_FILE_NAME=".dbwebb.course"
+
+dir="$DBW_CURRENT_DIR/."
+while [ "$dir" != "/" ]; do 
+    dir=$( dirname "$dir" )
+    found="$( find "$dir" -maxdepth 1 -name $DBW_COURSE_FILE_NAME )"
+    if [ "$found" ]; then 
+        DBW_COURSE_DIR="$( dirname $found )"
+        break
+    fi
+done
+
+
+
+# Where is the directory for the course repos, if any
+DBW_BASEDIR="dbwebb-kurser"
+if [ -d "$DBWEBB_HOME" ]; then
+    DBW_HOME="$DBW_BASEDIR"
+elif [ -d "$HOME/$DBW_BASEDIR" ]; then
+    DBW_HOME="$HOME/$DBW_BASEDIR"
+fi
+
+
+
+# Get the name of the course as $DBW_COURSE
+DBW_COURSE_FILE="$DBW_COURSE_DIR/$DBW_COURSE_FILE_NAME"
+DBW_COURSE_REPO_VALID=""
+if [ -f "$DBW_COURSE_FILE" ]; then
+    DBW_COURSE_REPO_VALID="yes"
+    source "$DBW_COURSE_FILE"
+fi
+
+
+
+# Where is the .dbwebb.config-file
+DBW_CONFIG_DEFAULT_FILE="$DBW_INSTALL_DIR/dbwebb2-config-sample"
+DBW_CONFIG_FILE_NAME=".dbwebb.config"
+DBW_CONFIG_FILE="$HOME/$DBW_CONFIG_FILE_NAME"
+if [ ! -f "$DBW_CONFIG_FILE" ]; then
+
+    # If the command is to init-repo, then execute that and create a config-file
+    if [ "$1" = "init-repo" ]; then
+        createConfig
+        exit 0
+    fi
+else
+    source "$DBW_CONFIG_FILE"
+fi
+
+# Name the remote server
+DBW_HOST="ssh.student.bth.se"
+
+# Check OS
+DBW_OS="$( uname -a )"
+
+# Create the ssh-command with details from the config-file
+SSH_CMD="$SSH ${DBW_USER}@${DBW_HOST} $DBW_SSH_KEY_OPTION"
+
+# Create the basis for the upload command
+RSYNC_CMD="$RSYNC -av --delete --exclude .git --exclude .gitignore -e \"ssh $DBW_SSH_KEY_OPTION\""
+RSYNC_DOWNLOAD_CMD="$RSYNC -avu -e \"ssh $DBW_SSH_KEY_OPTION\""
+
+DBW_REMOTE_DESTINATION="${DBW_USER}@${DBW_HOST}:$DBW_BASEDIR/$DBW_COURSE"
+
+
+
+# --------------- DBWEBB BOOTSTRAP PHASE END ---------------
+# --------------- DBWEBB-VALIDATE MAIN START HERE ---------------
+#
+# External tools
+#
+JSHINT="jshint"
+HTMLHINT="dbwebb-htmlhint"
+CSSHINT="htmlhint"
+
+HTML_MINIFIER="html-minifier"
+# TODO use DBW_COURSE_DIR
+HTML_MINIFIER_OPTIONS="--config-file ./.html-minifier.conf"
+
+UGLIFYJS="uglifyjs"
+UGLIFYJS_OPTIONS="--mangle --compress --screw-ie8 --comments"
+
+CLEANCSS="cleancss"
+CLEANCSS_OPTIONS="--s1 --skip-import"
+
+PYLINT="pylint"
+# TODO use DBW_COURSE_DIR
+PYLINT_OPTIONS="-r n --rcfile ./.pylintrc"
+
+
+
+#
+# Settings for this script
+#
+#umask 022
+export NODE_PATH=/usr/local/lib/node_modules
+
+
+
+#
+# Check for installed tools
+#
+function checkInstalledValidateTools
 {
-    WHAT="$1"
-    WHERE="$2"
-    ITEM="$3"
-    SUBDIR=""
+    printf "\nCheck for installed validation tools."
+    printf "\n"
+    printf " pylint:        %s\n" "$( checkCommand $PYLINT )"
+    printf " htmlhint:      %s\n" "$( checkCommand $HTMLHINT )"
+    printf " csshint:       %s\n" "$( checkCommand $CSSHINT )"
+    printf " jshint:        %s\n" "$( checkCommand $JSHINT )"
 
-    createUploadDownloadPaths
-    setChmod
+    if [[ $doPublish ]]; then 
 
-    local LOG="$HOME/.dbwebb-validate.log"
-    local INTRO="I will now upload files to the remote server and validate them."
-    local COMMAND1="$RSYNC_CMD '$WHAT' '$WHERE'"
-    local COMMAND2="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; dbwebb-validate -n $IGNORE_FAULTS $WHAT' | tee '$LOG';"
-    local MESSAGE="to validate course results. Saved a log of the output, review it as:\nless -R '$LOG'"
-    executeCommand "$INTRO" "$COMMAND1; $COMMAND2" "$MESSAGE"
+        printf " html-minifier: %s\n" "$( checkCommand $HTML_MINIFIER )"
+        printf " uglifyjs:      %s\n" "$( checkCommand $UGLIFYJS )"
+        printf " cleancss:      %s\n" "$( checkCommand $CLEANCSS )"
+    fi
+
+    printf "\n"
 }
 
 
 
-# --------------- DBWEBB FUNCTIONS PHASE END ---------------
+#
+# Perform an assert
+#
+function assert()
+{
+    EXPECTED=$1
+    TEST=$2
+    MESSAGE=$3
+    ASSERTS=$(( $ASSERTS + 1 ))
+
+    sh -c "$TEST" > "$TMPFILE" 2>&1
+    STATUS=$?
+    ERROR=$(cat $TMPFILE)
+
+    if [ \( ! $STATUS -eq $EXPECTED \) -o \( ! -z "$ERROR" \) ]; then
+        FAULTS=$(( $FAULTS + 1 ))
+
+        printf "\n\n$MSG_WARNING $MESSAGE\n" 
+        [ -z "$ERROR" ] || printf "$ERROR\n\n"
+    fi
+
+    return $STATUS
+}
+
+
+
+#
+# Clean up and output results from asserts
+#
+function assertResults()
+{
+    rm -f "$TMPFILE"
+    
+    if [ $FAULTS -gt 0 ]
+        then
+        printf "\n\n$MSG_FAILED"
+        printf " Asserts: $ASSERTS Faults: $FAULTS\n\n"
+        exit 1
+    fi
+    
+    printf "\n\n$MSG_OK"
+    printf " Asserts: $ASSERTS Faults: $FAULTS\n\n"
+    exit 0
+}
+
+
+
+#
+# Perform validation tests
+#
+function validateHtmlCssJs()
+{
+    local dir="$1"
+
+    printf "\n *.html using HTMLHint."
+    for filename in $(find "$dir/" -type f -name '*.html'); do
+        assert 0 "$HTMLHINT $filename" "HTMLHINT failed: $filename"
+    done
+
+    printf "\n *.js using JSHint."
+    for filename in $(find "$dir/" -type f -name '*.js'); do
+        assert 0 "$JSHINT $filename" "JSHint failed: $filename"
+    done
+}
+
+
+
+#
+# Perform validation tests
+#
+function validatePython()
+{
+    local dir="$1"
+
+    printf "\n *.py using Pylint."
+    for filename in $(find "$dir/" -type f -name '*.py'); do
+        assert 0 "$PYLINT $PYLINT_OPTIONS $filename" "pylint failed: $filename"
+    done
+
+    printf "\n *.cgi using Pylint."
+    for filename in $(find "$dir/" -type f -name '*.cgi'); do
+        assert 0 "$PYLINT $PYLINT_OPTIONS $filename" "pylint failed: $filename"
+    done
+}
+
+
+
+# ----------------------------------------- TO BE VALIDATED --------------------
+
+
+#
+# Init the build directory
+#
+initBuildDir()
+{
+    ME="$BUILD/me"
+    for dir in $BUILD1 $BUILD2 $BUILD3 $BUILD $ME $ME/kmom01 $ME/kmom02 $ME/kmom03 $ME/kmom04 $ME/kmom05 $ME/kmom06 $ME/kmom10; do
+        if [ ! -d $dir ]; then mkdir $dir; fi
+    done
+}
+
+
+
+#
+# Publish all
+#
+publishChmod()
+{
+    DIR="$1"
+
+    #find $BUILD/$dir/ -type d -print0 | xargs -0 chmod 755 
+    #find $BUILD/$dir/ -type f -print0 | xargs -0 chmod 644
+    #find $BUILD/$dir/ -type f -name '*.cgi' -print0 | xargs -0 chmod 755
+    #find $BUILD/$dir/ -type f -name '*.py'  -print0 | xargs -0 chmod 600
+
+    for filename in $(find "$DIR" -type d); do
+        chmod 755 "$filename"
+    done
+
+    for filename in $(find "$DIR" -type f); do
+        chmod 644 "$filename"
+    done
+
+    for filename in $(find "$DIR" -type f -name '*.cgi'); do
+        chmod 755 "$filename"
+    done
+
+    for filename in $(find "$DIR" -type f -name '*.py'); do
+        chmod 600 "$filename"
+    done
+}
+
+
+
+#
+# Publish all
+#
+publish()
+{
+    DIR="$1"
+    SILENT="$2"
+
+    if [ -z "$SILENT" ]; then
+        printf "\n\nPublishing $DIR to www/$BASEDIR/$PROJECT."
+    fi
+   
+    case "$DIR" in
+        example)    DIRS="example" ;;
+        tutorial)   DIRS="tutorial" ;;
+        me)         DIRS="me" ;;
+        all)        DIRS="example tutorial me" ;;
+        kmom*)      DIRS="me/js me/style $DIR" ;;
+        *)          DIRS="$DIR" ;;
+    esac
+
+    rsync -a --delete --exclude 'me/default' -f '- /*/' $TARGET/me/ $BUILD/me/
+    
+    publishChmod "$BUILD/me/"
+
+    for filename in $(find $BUILD/me/ -maxdepth 1 -type f -name '*.html'); do
+        assert 0 "$HTML_MINIFIER $HTML_MINIFIER_OPTIONS $filename --output $filename" "HTMLMinifier failed: $filename"
+    done
+
+    for filename in $(find $BUILD/me/ -maxdepth 1 -type f -name '*.js'); do
+        assert 0 "$UGLIFYJS $filename -o $filename $UGLIFYJS_OPTIONS" "UglifyJS failed: $filename"
+    done
+
+    for filename in $(find $BUILD/me/ -maxdepth 1 -type f -name '*.css'); do
+        assert 0 "$CLEANCSS $filename -o $filename" "CleanCSS failed: $filename"
+    done
+
+    #find "$BUILD/me/" -maxdepth 1 -type f -name '*.html' | while read filename; do $HTML_MINIFIER $HTML_MINIFIER_OPTIONS $filename --output $filename; exit; done
+    #find "$BUILD/me/" -maxdepth 1 -type f -name '*.js'   | while read filename; do $UGLIFYJS $filename -o $filename $UGLIFYJS_OPTIONS; done
+    #find "$BUILD/me/" -maxdepth 1 -type f -name '*.css'  | while read filename; do $CLEANCSS $filename -o $filename; done
+
+    for dir in $DIRS; do
+        if [ ! -d "$TARGET/$dir" ]; then continue; fi
+
+        printf "\n $dir:"
+        rsync -a --delete $TARGET/$dir/ $BUILD/$dir/ 
+        
+        publishChmod "$BUILD/$dir/"
+
+        if [ -z "$SILENT" ]; then printf " minify *.html"; fi
+        #find "$BUILD/$dir/" -type f -name '*.html' | while read filename; do assert "0" "$HTML_MINIFIER $HTML_MINIFIER_OPTIONS $filename --output $filename" "HTMLMinifier failed: $filename"; done
+        for filename in $(find "$BUILD/$dir/" -type f -name '*.html'); do
+            assert 0 "$HTML_MINIFIER $HTML_MINIFIER_OPTIONS $filename --output $filename" "HTMLMinifier failed: $filename"
+        done
+
+        if [ -z "$SILENT" ]; then printf " uglify *.js"; fi
+        #$UGLIFYJS $BUILD/$KMOM/$DIR/js/main.js -o $BUILD/$KMOM/$DIR/js/main.js $UGLIFYJS_OPTIONS
+        #find "$BUILD/$dir/" -type f -name '*.js' | while read filename; do assert "0" "$UGLIFYJS $filename -o $filename $UGLIFYJS_OPTIONS" "UglifyJS failed: $filename"; done
+        for filename in $(find "$BUILD/$dir/" -type f -name '*.js'); do
+            assert 0 "$UGLIFYJS $filename -o $filename $UGLIFYJS_OPTIONS" "UglifyJS failed: $filename"
+        done
+
+        
+        if [ -z "$SILENT" ]; then printf " minify *.css"; fi
+        #$CLEANCSS $BUILD/$KMOM/$DIR/style/style.css -o $BUILD/$KMOM/$DIR/style/style.css
+        #find "$BUILD/$dir/" -type f -name '*.css' | while read filename; do assert "0" "$CLEANCSS $filename -o $filename" "CleanCSS failed: $filename"; done
+        for filename in $(find "$BUILD/$dir/" -type f -name '*.css'); do
+            assert 0 "$CLEANCSS $filename -o $filename" "CleanCSS failed: $filename"
+        done
+
+    done
+}
+
+
+
+#
+# Process options
+#
+while (( $# ))
+do
+    case "$1" in
+        
+        --check | -c)
+            optCheck="yes"
+            shift
+            ;;
+
+        --publish | -p)
+            optPublish="yes"
+            shift
+            ;;
+
+        --help | -h)
+            printf %s "${usage[@]}"
+            exit 0
+        ;;
+        
+        --version | -v)
+            printf %s "${version[@]}"
+            exit 0
+        ;;
+                
+        *)
+            if [[ $command ]]; then
+                printf "$MSG_FAILED Too many options/items and/or option not recognized.\n\n"
+                printf %s "${badUsage[@]}"
+                exit 1
+            else
+                command=$1
+            fi
+            shift
+        ;;
+        
+    esac
+done
+
+
+
+#
+# Get the path to check
+#
+dir="$( getPathToDirectoryFor $command )"
+
+
+
+#
+# Do check for installed tools
+#
+if [[ $optCheck ]]; then checkInstalledValidateTools; fi
+    
+    
+    
+#
+# Validate
+#
+printf "\nValidate directory '$dir'"
+assert 0 "[ -d \"$dir\" ]" "Missing directory to validate: '$dir'"
+validateHtmlCssJs "$dir" 
+validatePython "$dir"
+
+
+
+# TODO Validate for another user?
+#THETARGET="$TARGET"
+#if [ ! -z "$THEUSER" ]
+#then
+#    THETARGET=`eval echo "~$THEUSER/dbwebb-kurser/$COURSE"`
+#fi
+
+
+
+#
+# Publish
+#
+if [[ $optPublish ]]; then
+    initBuildDir
+    publish "$dir"
+fi
+
+
+
+#
+# Wrap it up
+#
+assertResults
