release v2.0.0

diff --git a/dbwebb2 b/dbwebb2
--- a/dbwebb2
+++ b/dbwebb2
@@ -423,28 +423,6 @@ mapCmdToDir()
     fi
 
     case "$DBW_COURSE" in
-        htmlphp)
-            case "$CMD" in
-                me1)        RES="me/kmom01/me1" ;;
-                me2)        RES="me/kmom02/me2" ;;
-                me3)        RES="me/kmom03/me3" ;;
-                me4)        RES="me/kmom04/me4" ;;
-                me5)        RES="me/kmom05/me5" ;;
-                me6)        RES="me/kmom06/me6" ;;
-
-                multi)      RES="me/kmom03/multi" ;;
-                stylechooser) RES="me/kmom04/stylechooser" ;;
-                jetty)      RES="me/kmom05/jetty" ;;
-                bmo)        RES="me/kmom10/bmo" ;;
-
-                lab1)       RES="me/kmom02/lab1" ;;
-                lab2)       RES="me/kmom03/lab2" ;;
-                lab3)       RES="me/kmom04/lab3" ;;
-                lab4)       RES="me/kmom05/lab4" ;;
-                lab5)       RES="me/kmom06/lab5" ;;
-            esac
-            ;;
-
         javascript1)
             case "$CMD" in
                 sandbox)      RES="me/kmom01/sandbox" ;;
@@ -1737,10 +1715,15 @@ dbwebb-create()
     checkIfValidConfigOrExit
     checkIfValidCourseRepoOrExit
 
-    local lab_version=
-    [[ $version ]] && lab_version=" ($DBW_LAB_VERSION)"
+    # If no lab version supplied, read it from course repo if available
+    if [ -z "$version" -a -f "$DBW_COURSE_DIR/.dbwebb/lab.version" ]; then
+        version=$( cat $DBW_COURSE_DIR/.dbwebb/lab.version )
+    fi
 
-    printf "Creating $DBW_COURSE $lab{$lab_version} in '$where'.\n"
+    local lab_version=
+    [[ $version ]] && lab_version=" ($version)"
+
+    printf "Creating $DBW_COURSE $lab${lab_version} in '$where'.\n"
 
     # Check if init was run?
     if [ ! -d "$where" ]; then
@@ -1770,8 +1753,13 @@ dbwebb-create()
     printf "Downloading and extracting lab bundle\n"
     [[ $VERY_VERBOSE ]] && echo " ($DBW_LABURL/$bundleQuery)"
     [[ $VERY_VERBOSE ]] && echo " ($myWget $where/bundle.tar '$DBW_LABURL/$bundleQuery')"
+
     $myWget "$where/bundle.tar" "$DBW_LABURL/$bundleQuery"
+    [[ $? > 0 ]] && printf "$MSG_FAILED Failed to download lab bundle.\n" && exit 1
+
     tar -xmf "$where/bundle.tar" -C "$where"
+    [[ $? > 0 ]] && printf "$MSG_FAILED The downloaded lab bundle is not a tar archive. You may cat it to check for errors.\n" && exit 1
+
     rm -f "$where/bundle.tar"
     if [[ $save ]]; then
         moveLabAnswer "$where" "_$$" ""
