updating inspect for python

diff --git a/dbwebb-inspect b/dbwebb-inspect
--- a/dbwebb-inspect
+++ b/dbwebb-inspect
@@ -19,6 +19,9 @@ find /tmp -maxdepth 1 -name 'dbwebb-error*' -user mosstud -type f -exec rm -f {}
 #SUDO="sudo -A -u dbwebb"
 SUDO=""
 
+WRAP_HEADER="\n\n\n-------------------------------------------------------------"
+WRAP_FOOTER="\n-------------------------------------------------------------"
+
 
 
 #
@@ -56,84 +59,67 @@ printUsage()
 
 
 #
-# Check the environment
+# Write header for each test
 #
-checkEnvironment()
+headerForTest()
 {
-    $ECHO "\n-----------------------------------------"
-    $ECHO "\n----------- dbwebb inspect --------------"
-    $ECHO "\n-----------------------------------------"
+    what="$1"
+    task="$2"
 
-    # Check who you are
-    if [ "$USER" = "$THEUSER" ]
-    then
-        $ECHO "\nChecking your own $KMOM, ok."
-    else
-        $ECHO "\nChecking $KMOM for $THEUSER as `whoami` at `hostname`."
+    $ECHO "$WRAP_HEADER"
+    $ECHO "\n$what"
+    if [ ! -z "$task" ]; then
+        $ECHO "\n$task"
     fi
+    $ECHO "$WRAP_FOOTER"
+}
 
-    dirname="$THEDIR"
-    assert 0 "test -r $dirname -a -d $dirname" "Directory $dirname not readable.\nPerhaps login to the studserver and execute the command:\nsudo setpre-dbwebb-kurser.bash $THEUSER"
-    
-    if [ $? -eq 1 ]; then
-        $ECHO "\nFor debug:"
-        $ECHO "\n`whoami`\n"
-        $ECHO "\n`groups`\n"
 
-        dir="$( dirname $THEDIR )"
-        $ECHO "\n`ls -ld $dir`\n"
-        $ECHO "\n$dir is directory `test -d $dir; echo $?`\n"
-        $ECHO "\n$dir is readable `test -r $dir; echo $?`\n"
-
-        $ECHO "\n`ls -ld $THEDIR`\n"
-        $ECHO "\n$THEDIR is directory `test -d $THEDIR; echo $?`\n"
-        $ECHO "\n$THEDIR is readable `test -r $THEDIR; echo $?`\n"
-    fi 
+#
+# Open viles in editor
+#
+openFilesInEditor()
+{
+    where="$THEDIR/$1"
 
     $ECHO "\nOpen files in an editor:"
-    $ECHO "\n$EDITOR $dirname"
+    $ECHO "\n$EDITOR \"$where\""
+    $ECHO "\n"
+}
+
+
+#
+# Change to directory
+#
+changeToDirectory()
+{
+    where="$1"
 
     $ECHO "\nChange to directory:"
-    $ECHO "\ncd $dirname"
+    $ECHO "\ncd \"$where\""
+    $ECHO "\n"
 }
 
 
 
 #
-# Publish kmom to webserver
+# Print url and check if it exists
 #
-publishKmom()
+printUrl()
 {
-    target="$1"
-    answer="$2"
+    what="$1"
+    where="$2"
+    url="$SERVERURL/~$THEUSER/$BASEDIR/$PROJECT"
+    
+    $ECHO "\nURL to $what: $url/$where/$what"
 
-    if [ -z "$answer" ]; then 
-        $ECHO "\nPublish $THEKMOM [yN]? "
-
-        read answer
-        default="n"
-        answer=${answer:-$default}
-    else 
-        $ECHO "\nPublishing $THEKMOM."
-    fi;
-
-    if [ "$answer" = "y" -o "$answer" = "Y" ]
-    then
-        rsync -a --delete "$THEDIR/$target/" "$PUBLISH_STUD/"
-        
-        for filename in $(find "$PUBLISH_STUD" -type f -name '*.cgi'); do
-            chmod 755 "$filename"
-        done
-
-        url="$SERVERURL/~$USER/$BASEDIR/$STUD_DIR"
-        $ECHO "\nLink: $url"
-
-        $ECHO "\nOpen files in an editor:"
-        $ECHO "\n$EDITOR $PUBLISH_STUD/"
-
-        $ECHO "\nMove to the directory:"
-        $ECHO "\ncd $PUBLISH_STUD/"
+    if [ -z "$what" ]; then
+        assert 0 "test -d \"$THEDIR/$where\"" "The directory $where is missing or not readable."
+    else
+        assert 0 "test -f \"$THEDIR/$where/$what\"" "The file $what is missing or not readable."
     fi
+
+    $ECHO "\n"
 }
 
 
@@ -150,49 +136,128 @@ checkKmomDir()
 
 
 #
-# Execute a command, maybe as another user
+# Test check the file exists and is readable
 #
-executeCommand()
+fileIsReadable()
 {
-    what="$1"
-    move1="$2"
-    acmd="$3"
-    move2="$4"
-    opts="$5"
+    filename="$THEDIR/$1"
+    assert 0 "test -r $filename" "The file $filename is not readable."
+}
 
-    filename="$move1/$what"
 
-    if [ -f "$filename" -o -r "$filename" ]; then
-        $ECHO "\nExecute the program $what $opts [Yn]? "
-        read answer
-        default="y"
-        answer=${answer:-$default}
 
-        if [ "$answer" = "y" -o "$answer" = "Y" ]; then
+#
+# Press enter to continue
+#
+pressEnterToContinue()
+{
+    $ECHO "\nPress enter to continue..."
+    read void
+}
 
-            cd "$move1"
 
-            if [ "$USER" = "$THEUSER" ]; then
-                $cmda
-            else
-                $SUDO $cmda
-            fi
-            
-            status=$?
-            cd "$move2"
 
-            if [ $status -eq 0 ]; then
-                assert 1 "test" "Command executed successfully."
-                $ECHO "\n\n$MSG_OK Command executed with a exit status 0  - indicating success.\n"
-            else
-                assert 0 "test" "Command return non-zero exit status which might indicate failure.\n"
-            fi
-        fi
+#
+# Check the environment
+#
+checkEnvironment()
+{
+    headerForTest "-- dbwebb inspect"
+
+    # Check who you are
+    if [ "$USER" = "$THEUSER" ]
+    then
+        $ECHO "\nChecking your own $KMOM, ok."
     else
-        assert 0 "test" "The file $what is missing or not readable."
+        $ECHO "\nChecking $KMOM for $THEUSER as `whoami` at `hostname`."
+    fi
+
+    $ECHO "\n"
+
+    dirname="$THEDIR"
+    if [ ! -d "$dirname" ] 
+    then 
+        $ECHO "\n$MSG_FAILED Directory $dirname not readable.\n\nPerhaps login to the studserver and execute the command:\nsudo setpre-dbwebb-kurser.bash $THEUSER"
+
+        #$ECHO "\nFor debug:"
+        #$ECHO "\n`whoami`\n"
+        #$ECHO "\n`groups`\n"
+
+        #dir="$( dirname $THEDIR )"
+        #$ECHO "\n`ls -ld $dir`\n"
+        #$ECHO "\n$dir is directory `test -d $dir; echo $?`\n"
+        #$ECHO "\n$dir is readable `test -r $dir; echo $?`\n"
+
+        #$ECHO "\n`ls -ld $THEDIR`\n"
+        #$ECHO "\n$THEDIR is directory `test -d $THEDIR; echo $?`\n"
+        #$ECHO "\n$THEDIR is readable `test -r $THEDIR; echo $?`\n"
+
+        $ECHO "\n\nPress CTRL-C and fix it."
+        read answer
+    fi 
+
+    printUrl "" "me"
+    openFilesInEditor ""
+    changeToDirectory "$dirname"
+}
+
+
+
+#
+# Publish task if needed 
+#
+publishPath()
+{
+    if [ ! "$THEUSER" = "$USER" ]; then
+        $ECHO "\nMaking a local copy before testing..."
+        $ECHO "\n"
+
+        publishKmom "$1" "y"
+        TARGET_DIR="$PUBLISH_STUD"
+
+        $ECHO "\n...done."
+        $ECHO "\n"
+    else 
+        TARGET_DIR="$THEDIR/$1"
     fi
 }
 
+
+
+#
+# Publish kmom to webserver
+#
+publishKmom()
+{
+    target="$1"
+    answer="$2"
+
+    if [ -z "$answer" ]; then 
+        $ECHO "\nPublish $THEKMOM $target [yN]? "
+
+        read answer
+        default="n"
+        answer=${answer:-$default}
+    else 
+        $ECHO "\nPublishing $THEKMOM $target."
+    fi;
+
+    if [ "$answer" = "y" -o "$answer" = "Y" ]
+    then
+        rsync -a --delete "$THEDIR/$target/" "$PUBLISH_STUD/"
+        
+        for filename in $(find "$PUBLISH_STUD" -type f -name '*.cgi'); do
+            chmod 755 "$filename"
+        done
+
+        url="$SERVERURL/~$USER/$BASEDIR/$STUD_DIR"
+        $ECHO "\nURL: $url"
+        $ECHO "\n"
+
+        openFilesInEditor "$target"
+        changeToDirectory "$PUBLISH_STUD"
+    fi
+}
 
 
 
@@ -218,6 +283,54 @@ validateKmom()
 
 
 #
+# Execute a command, maybe as another user
+#
+executeCommand()
+{
+    what="$1"
+    move1="$2"
+    acmd="$3"
+    move2="$4"
+    opts="$5"
+
+    filename="$move1/$what"
+
+    if [ -f "$filename" -o -r "$filename" ]; then
+        $ECHO "\nExecute: $what $opts [Yn]? "
+        read answer
+        default="y"
+        answer=${answer:-$default}
+
+        if [ "$answer" = "y" -o "$answer" = "Y" ]; then
+
+            cd "$move1"
+
+            if [ "$USER" = "$THEUSER" ]; then
+                $acmd
+            else
+                $SUDO $acmd
+            fi
+            
+            status=$?
+            cd "$move2"
+
+            if [ $status -eq 0 ]; then
+                assert 1 "test" "Command executed successfully."
+                $ECHO "\n$MSG_OK Command executed with a exit status 0  - indicating success."
+                $ECHO "\n"
+            else
+                assert 0 "test" "Command return non-zero exit status which might indicate failure."
+            fi
+        fi
+    else
+        assert 0 "test" "The file $what is missing or not readable."
+    fi
+}
+
+
+
+
+#
 # Perform an assert
 #
 assert()
@@ -235,7 +348,7 @@ assert()
     if [ \( ! $STATUS -eq $EXPECTED \) -o \( ! -z "$ERROR" \) ]; then
         FAULTS=$(( $FAULTS + 1 ))
 
-        MSG="\n\n$MSG_FAILED $MESSAGE\n"
+        MSG="\n$MSG_FAILED $MESSAGE\n"
 
         $ECHO "$MSG" 
         [ -z "$ERROR" ] || $ECHO "$ERROR\n\n"
@@ -266,11 +379,10 @@ assertExit()
     if [ $STATUS -ne $EXPECTED ]; then
         FAULTS=$(( $FAULTS + 1 ))
 
-        $ECHO "\n\n$MSG_FAILED $MESSAGE\n"
+        $ECHO "\n$TEST"
+        $ECHO "\n$MSG_FAILED $MESSAGE\n"
 
         FAILED=1
-    else 
-        $ECHO "\n\n$MSG_OK\n"
     fi
 
     return $FAILED
@@ -350,17 +462,20 @@ case "$KMOM" in
 esac
 
 
-
+#
 # Clean up and output results
-if [ $FAULTS -gt 0 ]
-then
+#
+headerForTest "-- dbwebb inspect summary"
+
+if [ $FAULTS -gt 0 ]; then
         $ECHO "\n\n$MSG_FAILED"
         STATUS=1
-
-        $ECHO " Tests: $TESTS Asserts: $ASSERTS Faults: $FAULTS\n"
-        exit $STATUS
+else 
+        $ECHO "\n\n$MSG_OK"
+        STATUS=0
 fi
 
-$ECHO "\n\n$MSG_OK"
-$ECHO " Tests: $TESTS Asserts: $ASSERTS Faults: $FAULTS\n"
-exit 0
+#$ECHO " Tests: $TESTS Asserts: $ASSERTS Faults: $FAULTS\n"
+$ECHO " Tests: $ASSERTS Faults: $FAULTS\n"
+pressEnterToContinue
+exit $STATUS
