cleaning up before vt15

diff --git a/dbwebb2 b/dbwebb2
--- a/dbwebb2
+++ b/dbwebb2
@@ -11,6 +11,7 @@ SED="sed"
 WGET="wget"
 CURL="curl"
 BASH="bash"
+FIND="find"
 
 
 # Revise these
@@ -26,7 +27,7 @@ UPLOAD_MINIMAL="$RSYNC -av --delete --exclude me --exclude tutorial --exclude ex
 # For early error messages, also exists in .dbwebb.config
 MSG_FAILED="\033[0;37;41mFAILED.\033[0m"
 
-# Whar was the command issued?
+# What was the command issued?
 DBW_EXECUTABLE="$( basename "$0" )"
 
 # Where is the executable
@@ -37,10 +38,10 @@ if [ -f "$DBW_EXECUTABLE_DIR/.dbwebb.version" ]; then
     DBW_INSTALL_DIR="$DBW_EXECUTABLE_DIR"
 elif [ -d "$DBWEBB_HOME" ]; then
     DBW_INSTALL_DIR="$DBWEBB_HOME"
-elif [ -d "$HOME/dbwebb-kurser/bin-dbwebb" ]; then
-    DBW_INSTALL_DIR="$HOME/dbwebb-kurser/bin-dbwebb"
+elif [ -d "$HOME/dbwebb-kurser/dbwebb-cli" ]; then
+    DBW_INSTALL_DIR="$HOME/dbwebb-kurser/dbwebb-cli"
 else 
-    $ECHO "$MSG_FAILED Could not determine the installation directory."
+    $ECHO "$MSG_FAILED Could not determine the installation directory.\n"
     exit 1
 fi
 
@@ -59,33 +60,46 @@ source "$DBW_FUNCTIONS_FILE"
 # What is the current directory
 DBW_CURRENT_DIR="$( pwd )"
 
-# What is the directory of the current course repo
-DBW_COURSE_DIR="$DBW_CURRENT_DIR"
+# What is the directory of the current course repo, find recursivly up the tree
+DBW_COURSE_FILE_NAME=".dbwebb.course"
+
+dir="$DBW_CURRENT_DIR/."
+while [ "$dir" != "/" ]; do 
+    dir=$( dirname "$dir" )
+    found="$( find "$dir" -maxdepth 1 -name $DBW_COURSE_FILE_NAME )"
+    if [ "$found" ]; then 
+        DBW_COURSE_DIR="$( dirname $found )"
+        break
+    fi
+done
+
+
 
 # Get the name of the course as $DBW_COURSE
-DBW_COURSE_FILE="$DBW_COURSE_DIR/.dbwebb.course"
-if [ ! -f "$DBW_COURSE_FILE" ]; then
-    $ECHO "$MSG_FAILED Missing file .dbwebb.course, this is not a valid course repo.\n"
-    exit 1
+DBW_COURSE_FILE="$DBW_COURSE_DIR/$DBW_COURSE_FILE_NAME"
+DBW_COURSE_REPO_VALID="no"
+if [ -f "$DBW_COURSE_FILE" ]; then
+    DBW_COURSE_REPO_VALID="yes"
+    source "$DBW_COURSE_FILE"
 fi
-source "$DBW_COURSE_FILE"
+
+
 
 # Where is the .dbwebb.config-file
 DBW_CONFIG_DEFAULT_FILE="$DBW_INSTALL_DIR/dbwebb2-config-sample"
 DBW_CONFIG_FILE_NAME=".dbwebb2.config"
-DBW_CONFIG_FILE="$DBW_COURSE_DIR/$DBW_CONFIG_FILE_NAME"
+DBW_CONFIG_FILE="$HOME/$DBW_CONFIG_FILE_NAME"
 if [ ! -f "$DBW_CONFIG_FILE" ]; then
 
     # If the command is to init-repo, then execute that and create a config-file
     if [ "$1" = "init-repo" ]; then
         createConfig
         exit 0
-    else
-        $ECHO "$MSG_FAILED Missing the file $DBW_CONFIG_FILE_NAME. This does NOT appear to be a valid course repo.\nHave you initiated this as a course repo? Run the following command in the root of the course repo:\n$DBW_EXECUTABLE init-repo\n\n"
-        exit 1
     fi
+else
+    source "$DBW_CONFIG_FILE"
 fi
-source "$DBW_CONFIG_FILE"
+
 
 
 # Check OS
@@ -100,14 +114,22 @@ RSYNC_CMD="$RSYNC -av --delete --exclude .git --exclude .gitignore -e \"ssh $DBW
 
 
 #
-# Main
+# Main, start by checking basic usage
 #
 if [ $# -lt 1 ]
 then
+    dbwebb2PrintShortUsage
+    exit 0
+elif [ "$1" == "help" ]; then
     dbwebb2PrintUsage
+    exit 0
+elif [ "$1" == "create-config" ]; then
+    createConfig
     exit 0
 fi
 
+
+# Check if config file is up to date
 updateConfigIfNeeded "update"
 
 
@@ -150,13 +172,22 @@ do
             ;;
 
         \?)
-            dbwebb2PrintUsage
+            dbwebb2Usage
             exit 1
             ;;
     esac
 done
 shift $((OPTIND - 1))
 
+
+
+
+
+#$ECHO "$MSG_FAILED Could not find file $DBW_COURSE_FILE_NAME, this is not a valid course repo.\n"
+#exit 1
+
+#$ECHO "$MSG_FAILED Missing the file $DBW_CONFIG_FILE_NAME. This does NOT appear to be a valid course repo.\nHave you initiated this as a course repo? Run the following command in the root of the course repo:\n$DBW_EXECUTABLE init-repo\n\n"
+#exit 1
 
 
 #
@@ -177,7 +208,7 @@ case $CMD in
         initServer
         ;;
 
-    environment)
+    env|environment)
         environment
         ;;
 
@@ -189,8 +220,8 @@ case $CMD in
         testConnection
         ;;
 
-    version)
-        version
+    status)
+        status
         ;;
 
     login)
@@ -255,7 +286,7 @@ case $CMD in
         ;;
 
     *)
-        dbwebb2PrintUsage
+        dbwebb2PrintShortUsage
         exit 1
         ;;
 esac
