create labs

diff --git a/dbwebb2-validate b/dbwebb2-validate
--- a/dbwebb2-validate
+++ b/dbwebb2-validate
@@ -36,12 +36,14 @@ function usage ()
 "  or absolute path"
 ""
 "Options:"
-"  -c, --check    Check installed tools."
-"  --selfupdate   Update to latest version."
-"  -d, --dry      Dry run, only display."
-"  -p, --publish  Publish it."
-"  -h, --help     Print help."
-"  -v, --version  Print version."
+"  -c, --check       Check installed tools."
+"  --selfupdate      Update to latest version."
+"  -d, --dry         Dry run, only display."
+"  --only extension  Only test for extension."
+"  -p, --publish     Publish it."
+"  --publish-to path Path where to publish."
+"  -h, --help        Print help."
+"  -v, --version     Print version."
 ""
 "Manual at: http://dbwebb.se/dbwebb-cli"
     )
@@ -120,12 +122,14 @@ function createConfig()
     remoteDir=${remoteDir:-dbwebb-kurser}
     remoteWww=${remoteWww:-www/dbwebb-kurser}
     baseurl=${baseurl:-http://www.student.bth.se/~$acronym/$remoteDir}
+    laburl=${laburl:-http://www.student.bth.se/~mosstud/kod-exempel/lab}
 
     echo "DBW_USER='$acronym'"               > "$DBW_CONFIG_FILE"
     echo "DBW_HOST='$remoteHost'"           >> "$DBW_CONFIG_FILE"
     echo "DBW_REMOTE_BASEDIR='$remoteDir'"  >> "$DBW_CONFIG_FILE"
     echo "DBW_REMOTE_WWWDIR='$remoteWww'"   >> "$DBW_CONFIG_FILE"
     echo "DBW_BASEURL='$baseurl'"           >> "$DBW_CONFIG_FILE"
+    echo "DBW_LABURL='$laburl'"             >> "$DBW_CONFIG_FILE"
 
     printf "$MSG_OK The config file '$DBW_CONFIG_FILE' is now up-to-date.\n"
 }
@@ -466,23 +470,6 @@ inspectResults()
 
 
 
-# --------------------- To be validated -------------------------------
-
-
-#
-# Create a lab
-#
-createLab()
-{
-    LAB="$1"
-    INTRO="Create laboration $LAB."
-    COMMAND="bin/dbwebb-create \"$LAB\""
-    MESSAGE="to create the lab."
-    executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
-}
-
-
-
 #------------------------- HERE ARE THE MAIN COMMANDS -------------------------------
 
 
@@ -750,6 +737,97 @@ function dbwebb-publish()
 
 
 #
+# Create a lab
+#
+dbwebb-create()
+{
+    local lab="$1"
+    local subdir="$( mapCmdToDir $lab )"
+    local where="$DBW_COURSE_DIR/$subdir"
+    
+    checkIfValidCourseRepoOrExit
+
+    printf "Creating $DBW_COURSE $lab in '$where'.\n"
+
+    # Check if init was run?
+    if [ ! -d "$where" ]; then
+        printf "$MSG_FAILED The directory '$where' is missing.\nDid you run the command 'dbwebb init'?\n"
+        exit 2
+    fi
+
+    # Check if lab is already there
+    if [ -f "$where/answer.php" -o -f "$where/answer.js" -o -f "$where/answer.py" ]; then
+        printf "$MSG_FAILED You have already created lab-files at: '$where'\nRemove the files in the directory, then you can generate new files.\n"
+        exit 2
+    fi
+
+    # Check for wget
+    local myWget
+
+    if hash wget 2> /dev/null; then
+        myWget="wget -qO"
+    elif hash curl 2> /dev/null; then
+        myWget="curl -so"
+    else
+        printf "$MSG_FAILED Missing wget and curl, can not create a lab without both.\n"
+        exit 2
+    fi
+
+    # Create the key
+    local getKey="action=only-key&acronym=$DBW_USER&course=$DBW_COURSE&doGenerate=Submit"
+    local key="$( ${myWget}- "$DBW_LABURL/?$getKey&lab=$lab" )"
+
+    # The lab description
+    local getLab="lab.php?lab"
+    printf " instruction.html"
+    $myWget "$where/instruction.html" "$DBW_LABURL/$getLab&key=$key"
+
+    # The lab documents
+    case "$DBW_COURSE" in
+        
+        htmlphp)
+            printf "\n answer.php"
+            $myWget "$where/answer.php" "$DBW_LABURL/lab.php?answer-php&key=$key"
+
+            printf "\n answer.json"
+            $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
+        ;;
+        
+        javascript1)
+            printf "\n answer.html"
+            $myWget "$where/answer.html" "$DBW_LABURL/lab.php?answer-html&key=$key"
+
+            printf "\n answer.js"
+            $myWget "$where/answer.js" "$DBW_LABURL/lab.php?answer-js&key=$key"
+        ;;
+
+        python)
+            printf "\n answer.json"
+            $myWget "$where/answer.json" "$DBW_LABURL/lab.php?answer-json&key=$key"
+
+            printf "\n answer.py"
+            $myWget "$where/answer.py" "$DBW_LABURL/lab.php?answer-py&key=$key"
+            chmod 755 "$where/answer.py"
+
+            printf "\n Dbwebb.py"
+            $myWget "$where/Dbwebb.py" "$DBW_LABURL/lab.php?answer-py-assert&key=$key"
+        ;;
+
+    esac
+
+    # Extras
+    local getAnswerExtra="lab.php?answer-extra"
+    printf "\n (extras)"
+    $myWget "$where/extra.tar" "$DBW_LABURL/$getAnswerExtra&key=$key"
+    tar -xvf "$where/extra.tar" -C "$where"
+    rm -f "$where/extra.tar"
+
+    printf "\n$MSG_DONE You can find the lab and all files here: '$where'\n"
+}
+
+
+
+#
 # Selfupdate
 #
 dbwebb-selfupdate()
@@ -954,7 +1032,10 @@ CHECKBASH_OPTIONS="--shell=bash"
 CHECKSH="shellcheck"
 CHECKSH_OPTIONS="--shell=sh"
 
+#YAML="dbwebb-js-yaml"
+#YAML_OPTIONS="--silent"
 YAML="js-yaml"
+YAML_OPTIONS=""
 
 if [[ $DBW_COURSE_DIR ]]; then
     HTML_MINIFIER_CONFIG="--config-file '$DBW_COURSE_DIR/.html-minifier.conf'"
@@ -1077,6 +1158,7 @@ function validateCommand()
     local cmd="$2"
     local extension="$3"
     local options="$4"
+    local output="$5"
     local counter=0
 
     if hash "$cmd" 2>/dev/null; then
@@ -1085,7 +1167,9 @@ function validateCommand()
             if [[ $optDryRun ]]; then
                 printf "\n%s" "$cmd $options $filename"
             else
-                assert 0 "$cmd $options $filename" "$cmd failed: $filename"
+                if [ -z $optOnly -o $optOnly == $extension ]; then
+                    assert 0 "$cmd $options $filename $output" "$cmd failed: $filename"
+                fi
             fi
             counter=$(( counter + 1 )) 
         done
@@ -1115,7 +1199,7 @@ function validate()
     validateCommand "$dir" "$PHPCS" "php" 
     validateCommand "$dir" "$CHECKBASH" "bash" "$CHECKBASH_OPTIONS" 
     validateCommand "$dir" "$CHECKSH" "sh" "$CHECKSH_OPTIONS"
-    validateCommand "$dir" "$YAML" "yml"
+    validateCommand "$dir" "$YAML" "yml" "$YAML_OPTIONS" " > /dev/null"
 }
 
 
@@ -1214,6 +1298,12 @@ do
                 exit 2
             fi
                 
+            shift
+            shift
+            ;;
+
+        --only)
+            optOnly="$2"
             shift
             shift
             ;;
