Added version info in dbwebb-validate check.

diff --git a/dbwebb2-inspect b/dbwebb2-inspect
--- a/dbwebb2-inspect
+++ b/dbwebb2-inspect
@@ -30,7 +30,7 @@
 #
 # Current version
 #
-DBW_VERSION="v1.9.43 (2016-05-16)"
+DBW_VERSION="v1.9.44 (2016-05-16)"
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -123,7 +123,7 @@ function createGithubUrl(){
 #
 # Check for installed commands
 #
-function checkCommand()
+function checkCommand
 {
     local COMMAND="$1"
 
@@ -133,6 +133,29 @@ function checkCommand()
         printf "$( which $COMMAND )"
     fi
 }
+
+
+
+#
+# Check command and version of it with nice string as result
+#
+function checkCommandWithVersion
+{
+    local what="$1"
+    local version="$2"
+    local options="$3"
+
+    if ! hash "$what" 2>/dev/null; then
+        printf "%-10s Command '%s' not found." "-" "$what"
+    else
+        if [ ! -z "$version" ]; then
+            printf "%-10s %s" "$( eval $what $version $options )" "$( which $what )"
+        else
+            printf "%-10s %s" "?" "$( which $what )"
+        fi
+    fi
+}
+
 
 
 
diff --git a/dbwebb2-validate b/dbwebb2-validate
--- a/dbwebb2-validate
+++ b/dbwebb2-validate
@@ -30,7 +30,7 @@
 #
 # Current version
 #
-DBW_VERSION="v1.9.43 (2016-05-16)"
+DBW_VERSION="v1.9.44 (2016-05-16)"
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -123,7 +123,7 @@ function createGithubUrl(){
 #
 # Check for installed commands
 #
-function checkCommand()
+function checkCommand
 {
     local COMMAND="$1"
 
@@ -133,6 +133,29 @@ function checkCommand()
         printf "$( which $COMMAND )"
     fi
 }
+
+
+
+#
+# Check command and version of it with nice string as result
+#
+function checkCommandWithVersion
+{
+    local what="$1"
+    local version="$2"
+    local options="$3"
+
+    if ! hash "$what" 2>/dev/null; then
+        printf "%-10s Command '%s' not found." "-" "$what"
+    else
+        if [ ! -z "$version" ]; then
+            printf "%-10s %s" "$( eval $what $version $options )" "$( which $what )"
+        else
+            printf "%-10s %s" "?" "$( which $what )"
+        fi
+    fi
+}
+
 
 
 
@@ -1000,7 +1023,7 @@ FILE_CRLF_OPTIONS=""
 FILE_BOM="file"
 FILE_BOM_OPTIONS=""
 
-PHPUGLIFY=""
+PHPUGLIFY="phpuglify"
 
 PHPMINIFY="php"
 PHPMINIFY_OPTIONS="--strip"
@@ -1058,27 +1081,31 @@ function setDefaultConfigFiles()
 function checkInstalledValidateTools
 {
     printf "Check for installed validation tools.\n"
-    printf " htmlhint:      %s\n" "$( checkCommand $HTMLHINT )"
-    printf " csslint:       %s\n" "$( checkCommand $CSSLINT )"
-    printf " jshint:        %s\n" "$( checkCommand $JSHINT )"
-    printf " jscs:          %s\n" "$( checkCommand $JSCS )"
-    printf " jsonlint:      %s\n" "$( checkCommand $JSONLINT )"
-    printf " pylint:        %s\n" "$( checkCommand $PYLINT )"
-    printf " php:           %s\n" "$( checkCommand $PHP )"
-    printf " phpmd:         %s\n" "$( checkCommand $PHPMD )"
-    printf " phpcs:         %s\n" "$( checkCommand $PHPCS )"
-    printf " bash:          %s\n" "$( checkCommand $CHECKBASH )"
-    printf " sh:            %s\n" "$( checkCommand $CHECKSH )"
-    printf " yaml:          %s\n" "$( checkCommand $YAML )"
-    printf " file CRLF:     %s\n" "$( checkCommand $FILE_CRLF )"
-    printf " file BOM:      %s\n" "$( checkCommand $FILE_BOM )"
+    printf " htmlhint:      %s\n" "$( checkCommandWithVersion $HTMLHINT "--version" )"
+    printf " csslint:       %s\n" "$( checkCommandWithVersion $CSSLINT "--version" )"
+    printf " jshint:        %s\n" "$( checkCommandWithVersion $JSHINT "--version" "2>&1 | cut -d ' ' -f 2" )"
+    printf " jscs:          %s\n" "$( checkCommandWithVersion $JSCS "--version" )"
+    printf " jsonlint:      %s\n" "$( checkCommandWithVersion $JSONLINT "" )"
+    printf " pylint:        %s\n" "$( checkCommandWithVersion $PYLINT "--version" "| head -1 | cut -d ' ' -f 2" )"
+    printf " php:           %s\n" "$( checkCommandWithVersion $PHP "--version" "| head -1 | cut -d ' ' -f 2" )"
+    printf " phpmd:         %s\n" "$( checkCommandWithVersion $PHPMD "--version" "| cut -d ' ' -f 2" )"
+    printf " phpcs:         %s\n" "$( checkCommandWithVersion $PHPCS "--version" "| cut -d ' ' -f 3" )"
+    printf " bash:          %s\n" "$( checkCommandWithVersion $CHECKBASH "--version" "| head -2 | tail -1 | cut -d ' ' -f 2" )"
+    printf " sh:            %s\n" "$( checkCommandWithVersion $CHECKSH "--version" "| head -2 | tail -1 | cut -d ' ' -f 2" )"
+    printf " yaml:          %s\n" "$( checkCommandWithVersion $YAML "--version" )"
+    printf " file CRLF:     %s\n" "$( checkCommandWithVersion $FILE_CRLF "--version" "| head -1" )"
+    printf " file BOM:      %s\n" "$( checkCommandWithVersion $FILE_BOM "--version" "| head -1" )"
 
     printf "Check for installed publishing tools.\n"
-    printf " html-minifier: %s\n" "$( checkCommand $HTML_MINIFIER )"
-    printf " cleancss:      %s\n" "$( checkCommand $CLEANCSS )"
-    printf " uglifyjs:      %s\n" "$( checkCommand $UGLIFYJS )"
-    printf " phpminify:     %s\n" "$( checkCommand $PHPMINIFY )"
-    printf " phpuglify:     %s\n" "$( checkCommand $PHPUGLIFY )"
+    printf " html-minifier: %s\n" "$( checkCommandWithVersion $HTML_MINIFIER "--version" "| cut -d ' ' -f 2" )"
+    printf " cleancss:      %s\n" "$( checkCommandWithVersion $CLEANCSS "--version" )"
+    printf " uglifyjs:      %s\n" "$( checkCommandWithVersion $UGLIFYJS "--version" "| cut -d ' ' -f 2" )"
+    printf " phpminify:     %s\n" "$( checkCommandWithVersion $PHPMINIFY "--version" "| head -1 | cut -d ' ' -f 2" )"
+    printf " phpuglify:     %s\n" "$( checkCommandWithVersion $PHPUGLIFY "--version" )"
+
+    printf "Check for other tools.\n"
+    printf " node:          %s\n" "$( checkCommandWithVersion "node" "--version" )"
+    printf " npm:           %s\n" "$( checkCommandWithVersion "npm" "--version" )"
 }
 
 
