adding clone to dbwebb

diff --git a/dbwebb2 b/dbwebb2
--- a/dbwebb2
+++ b/dbwebb2
@@ -34,6 +34,7 @@ function usage ()
 "  selfupdate   Update to latest version."
 "  sshkey       Create and install ssh-keys."
 "  login        Login to the remote server."
+"  clone        Clone a course repo."
 "  init         Init course repo and remote server."
 "  update       Update course repo."
 "  upload [part]     Upload to server."
@@ -724,7 +725,7 @@ function dbwebb-validate()
     local log="$HOME/.dbwebb-validate.log"
     local intro="Uploading the directory '$WHAT' to '$WHERE' for validation."
     local command1="$RSYNC_CMD '$WHAT' '$WHERE'"
-    local command2="$SSH_CMD 'dbwebb-validate \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' | tee '$log';"
+    local command2="$SSH_CMD 'cd \"$DBW_REMOTE_BASEDIR/$DBW_COURSE\"; dbwebb-validate \"$DBW_REMOTE_BASEDIR/$DBW_COURSE/$SUBDIR\"' | tee '$log';"
     local message="to validate course results.\nSaved a log of the output: less -R '$log'"
     executeCommand "$intro" "$command1; $command2" "$message"
 }
@@ -875,6 +876,39 @@ dbwebb-selfupdate()
     
     printf "Current version is: "
     dbwebb --version
+}
+
+
+
+#
+# Selfupdate
+#
+dbwebb-clone()
+{
+    local repo="$1"
+    local github=
+    
+    if [[ $repo ]]; then
+        case "$repo" in
+            python)      github="https://github.com/mosbth/python.git";;
+            javascript1) github="https://github.com/mosbth/javascript1.git";;
+            linux)       github="https://github.com/mosbth/linux.git";;
+            webapp)      github="https://github.com/mosbth/webapp.git";;
+            htmlphp)     github="https://github.com/mosbth/htmlphp.git";;
+            *)           printf "$MSG_FAILED Not a valid course rep: '$repo'\n"
+        esac
+    fi
+    
+    if [[ ! $github ]]; then
+        printf "Available course repos are: python, javascript1, linux, webapp or htmlphp.\n"
+        printf "Usage: dbwebb clone python\n"
+        exit 1
+    fi
+    
+    local intro="Cloning course-repo for '$repo' from '$github'."
+    local cmd="git clone \"$github\""
+    local message="to clone course repo '$repo' from '$github'."
+    executeCommand "$intro" "$cmd" "$message"
 }
 
 
@@ -1087,6 +1121,7 @@ do
 
         update         \
         | check        \
+        | clone        \
         | config       \
         | updateconfig \
         | selfupdate   \
