corrected jscs output

diff --git a/dbwebb2-inspect b/dbwebb2-inspect
--- a/dbwebb2-inspect
+++ b/dbwebb2-inspect
@@ -30,7 +30,7 @@
 #
 # Current version
 #
-DBW_VERSION="v1.9.4x (latest)"
+DBW_VERSION="v1.9.5 (2015-06-17)"
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -267,6 +267,7 @@ mapCmdToDir()
                 me2)        RES="me/kmom02/me2" ;;
                 me3)        RES="me/kmom03/me3" ;;
                 me4)        RES="me/kmom04/me4" ;;
+                me5)        RES="me/kmom05/me5" ;;
                 
                 multi)      RES="me/kmom03/multi" ;;
                 stylechooser) RES="me/kmom04/stylechooser" ;;
@@ -485,20 +486,26 @@ function assert()
     TEST=$2
     MESSAGE=$3
     ASSERTS=$(( $ASSERTS + 1 ))
+    local onlyExitStatus=$4
+    local error=
+    local status=
 
     bash -c "$TEST" &> "$TMPFILE"
-    STATUS=$?
-    ERROR=$( cat "$TMPFILE" )
+    status=$?
+    
+    if [ \( -z "$onlyExitStatus" \) -o \( ! $status -eq $EXPECTED \) ]; then
+        error=$( cat "$TMPFILE" )
+    fi
     rm -f "$TMPFILE"
 
-    if [ \( ! $STATUS -eq $EXPECTED \) -o \( ! -z "$ERROR" \) ]; then
+    if [ \( ! $status -eq $EXPECTED \) -o \( ! -z "$error" \) ]; then
         FAULTS=$(( $FAULTS + 1 ))
 
         printf "\n\n$MSG_WARNING $MESSAGE\n" 
-        [ -z "$ERROR" ] || printf "$ERROR\n\n"
+        [ -z "$error" ] || printf "$error\n\n"
     fi
 
-    return $STATUS
+    return $status
 }
 
 
diff --git a/dbwebb2-validate b/dbwebb2-validate
--- a/dbwebb2-validate
+++ b/dbwebb2-validate
@@ -30,7 +30,7 @@
 #
 # Current version
 #
-DBW_VERSION="v1.9.4x (latest)"
+DBW_VERSION="v1.9.5 (2015-06-17)"
 # --------------- DBWEBB FUNCTIONS PHASE START ---------------
 
 #
@@ -267,6 +267,7 @@ mapCmdToDir()
                 me2)        RES="me/kmom02/me2" ;;
                 me3)        RES="me/kmom03/me3" ;;
                 me4)        RES="me/kmom04/me4" ;;
+                me5)        RES="me/kmom05/me5" ;;
                 
                 multi)      RES="me/kmom03/multi" ;;
                 stylechooser) RES="me/kmom04/stylechooser" ;;
@@ -485,20 +486,26 @@ function assert()
     TEST=$2
     MESSAGE=$3
     ASSERTS=$(( $ASSERTS + 1 ))
+    local onlyExitStatus=$4
+    local error=
+    local status=
 
     bash -c "$TEST" &> "$TMPFILE"
-    STATUS=$?
-    ERROR=$( cat "$TMPFILE" )
+    status=$?
+    
+    if [ \( -z "$onlyExitStatus" \) -o \( ! $status -eq $EXPECTED \) ]; then
+        error=$( cat "$TMPFILE" )
+    fi
     rm -f "$TMPFILE"
 
-    if [ \( ! $STATUS -eq $EXPECTED \) -o \( ! -z "$ERROR" \) ]; then
+    if [ \( ! $status -eq $EXPECTED \) -o \( ! -z "$error" \) ]; then
         FAULTS=$(( $FAULTS + 1 ))
 
         printf "\n\n$MSG_WARNING $MESSAGE\n" 
-        [ -z "$ERROR" ] || printf "$ERROR\n\n"
+        [ -z "$error" ] || printf "$error\n\n"
     fi
 
-    return $STATUS
+    return $status
 }
 
 
@@ -866,6 +873,7 @@ function validateCommand()
     local extension="$3"
     local options="$4"
     local output="$5"
+    local onlyExitStatus="$6"
     local counter=0
 
     if hash "$cmd" 2>/dev/null; then
@@ -875,9 +883,9 @@ function validateCommand()
                 printf "\n%s" "$cmd $options $filename $output"
             else
                 if [ -z $optOnly  ]; then
-                    assert 0 "$cmd $options $filename $output" "$cmd failed: $filename"
+                    assert 0 "$cmd $options $filename $output" "$cmd failed: $filename" "$onlyExitStatus"
                 elif [ "$extension" == "$optOnly" ]; then
-                    assert 0 "$cmd $options $filename $output" "$cmd failed: $filename"
+                    assert 0 "$cmd $options $filename $output" "$cmd failed: $filename" "$onlyExitStatus"
                 fi
             fi
             counter=$(( counter + 1 )) 
@@ -900,7 +908,7 @@ function validate()
     [[ $DISABLE_HTMLHINT ]]  || validateCommand "$dir" "$HTMLHINT" "html" 
     [[ $DISABLE_CSSLINT ]]   || validateCommand "$dir" "$CSSLINT" "css" "$CSSLINT_OPTIONS $( cat "$CSSLINT_CONFIG" )"
     [[ $DISABLE_JSHINT ]]    || validateCommand "$dir" "$JSHINT" "js"
-    [[ $DISABLE_JSCS ]]      || validateCommand "$dir" "$JSCS" "js" "$JSCS_OPTIONS $JSCS_CONFIG" "| grep -v 'No code style errors found.'; exit ${PIPESTATUS[0]}"
+    [[ $DISABLE_JSCS ]]      || validateCommand "$dir" "$JSCS" "js"  "$JSCS_OPTIONS $JSCS_CONFIG" "" "onlyExitStatus"
     #validateCommand "$dir" "$JSCS" "js" "$JSCS_OPTIONS $JSCS_CONFIG" ""
     [[ $DISABLE_PYLINT ]]    || validateCommand "$dir" "$PYLINT" "py" "$PYLINT_OPTIONS $PYLINT_CONFIG" 
     [[ $DISABLE_PYLINT ]]    || validateCommand "$dir" "$PYLINT" "cgi" "$PYLINT_OPTIONS $PYLINT_CONFIG" 
